### ISSUE TITLE
zero-copy encapsulation

### ISSUE THREAD

**Issue by deemru** [luigirizzo/netmap#117]
Didn't find netmap API possibility of a full packet zero-copy encapsulation (new_hdr + old_pkt).

The current design seems to operate with buffers in slots which can only be appended.

Is there a opportunity to make buffers in slots prepended by adding sliding starting point which can be shifted backwards (user sets a max value of the shift in an initialization)?

**Comment by tbarbette** [comment]
In the TX side, if you set the NS_MOREFRAG flag on the first buffer, the next buffer will be appended and the two will be sent as one packet by the NIC. However not all drivers support this (ixgbe at least, and I've got code for i40e if you're interested).

For the RX side, there is currently no way to tell the NIC to write at a certain offset inside the buffer instead of the beginning. I've got code where I added a field to ask for some "headroom" when receiving packets, but once again I only made it work for the ixgbe driver... i40e port would be easy too.

**Comment by deemru** [comment]
The NS_MOREFRAG flag is a nice workaround on a TX side (encapsulation).

In most cases on a RX side (decapsulation) we need to cut headers and trailers. We can manipulate a length of a buffer easily, but we need to shift a start position in this slot or to skip/ignore these bytes at the beginning on a host stack. Is there a workaround for this case?

**Comment by deemru** [comment]
Just realised that we can skip cutted headers by adding empty options for ipv4 (extension headers for ipv6).
