### ISSUE TITLE
mmap() produce always different addresses

### ISSUE THREAD

**Issue by gureedo** [luigirizzo/netmap#126]
Take program bridge.c from examples. Remove netmap shared memory reusing
```c
// XXX use a single mmap ?
pb = nm_open(ifb, NULL, /*NM_OPEN_NO_MMAP*/ 0, /*pa*/ NULL);
```
Now I always got message zerocopy is not possible, even if I choose to connect hw rings with sw ring of same adatpter.

This is seems to be a bug in bridge or what?
```c
zerocopy = zerocopy && (pa->mem == pb->mem);
D("------- zerocopy %ssupported", zerocopy ? "" : "NOT ");
```

Using Debian 8.2.

**Comment by vmaffione** [comment]
What kind of devices are you opening?

**Comment by gureedo** [comment]
ixgbe device (intel 82599ES)

**Comment by vmaffione** [comment]
So you have two such devices and you want to bridge them together?

**Comment by gureedo** [comment]
Yes, but there is no problem to bridge such devices. I'm interested should mmap return same address on second call?

**Comment by vmaffione** [comment]
The underlying physical memory is the same, since you are using hardware interfaces. However, there is currently no way for the system to know that the underlying memory was already mapped, so you just get a different virtual address.

You should probably be able to do zerocopy even in this case, since netmap API uses offsets to access rings, buffers, etc.

**Comment by gureedo** [comment]
Thanks. So bridge example needs proper fix to not confuse users in feature.

**Comment by vmaffione** [comment]
Yes, I''ll just have to fix the outdated comment
````
XXX use a single mmap()
````

Thanks
