### ISSUE TITLE
Question: Has anyone tried netmap with vlan interface?

### ISSUE THREAD

**Issue by morphyno** [luigirizzo/netmap#133]
Is VLAN inteface with netmap supported? If I were to have eth0:1000, can I still invoke it as netmap:eth0:1000?

**Comment by vmaffione** [comment]
There are two strategies here:

1) your application uses nm_open("netmap:eth0"), and then sends/receives VLAN tagged Ethernet frames. In this case, if netmap has a patched driver for eth0 (e.g. ixgbe, e1000, etc.), you will be able to run at full speed.

2) your application uses nm_open("netmap:eth0.1000"), and then sends/receives normal (untagged) Ethernet frames. I've never tried this, but in this case you should fall back to the "emulation" (aka "generic") mode, because from an O.S. perspective a VLAN interface uses a separate "vlan" driver, which is not supported by netmap (and probably cannot be). So you should still be able to use netmap, but under the hood netmap would use the unpatched driver, which means you cannot go at full speed.

**Comment by morphyno** [comment]
Thanks @vmaffione, i have tried it and it looks nm_open against a VLAN interface is not truely by netmap. I wonder if its ever possible to patch the kernel standard 8021.Q VLAN driver to support netmap.

**Comment by vmaffione** [comment]
As I see it, It does not make sense to patch it, because the VLAN driver is jsut a meta-driver that uses another driver (the real one), see for instance

lxr.free-electrons.com/source/net/8021q/vlan_dev.c

In principle you could patch the VLAN driver, but then you must handle two cases: a) the underlying (real) driver has netmap support b) the underlying driver doesn't have netmap support and so falls back to emulation.

For case b), you are using emulation anyway, so it does not make sense to patch the VLAN driver, you wouldn't go faster.

For case a), your patched VLAN driver should insert the VLAN tag in the frame prepared by the netmap application (which in this case you don't want to be VLAN-aware), but you cannot do it without doing a copy of the frame, which means you would go slower.

As a consequence, the best option is just to make the application VLAN aware, that's it. Also, netmap is designed for application where you want to deal with packets at the lowest level, so you want to see Ethernet headers, IP headers, etc. Then, it does not make sense for netmap to abstract the VLAN, you have to deal with them manually because you want.

If you don't think you want to deal with Ethernet headers and VLANs, maybe you just don't want to use netmap (you want to use RAW sockets, for instance)

**Comment by morphyno** [comment]
Here is our usecase. We have a network monitoring application that's been using netmap for sometime. It works really well since it has many interfaces, and each interface is dedicated to a particular network segment. The benefit of netmap is that netmap-libpcap allows us and our customers to use off the shelf libpcap applications, which gave us performance enhancement and flexibility.

The use case arose when we are looking to port this solution running on smaller solution running on 1 interface. Multiple network segments are then VLAN tagged. The proposal is create many VLAN tagged interfaces that would strip respective VLANs. In order to fully leverage netmap in this case, I feel the best approach is to make the VLAN driver netmap aware.

**Comment by UlricE** [comment]
Can't you make your application VLAN aware?

**Comment by morphyno** [comment]
@UlricE, we actually provide a hardware platform and we support many libpcap based applications, so we don't own all the applications. We have been relying on the flexibility of netmap-libpcap to provide performance enhancement to off the shelf libpcap and our customer's applications (which we don't own the source code to)
