### ISSUE TITLE
Next official release?

### ISSUE THREAD

**Issue by morphyno** [luigirizzo/netmap#148]
Just out of curiosity, will there be an official release scheduled? The last official release is 11.1 from October of 2014. I have been running newer versions from github, but its hard to go to production without an official release version.

**Comment by morphyno** [comment]
Not to beat a dead horse. I have been running 11.1 for over a year for my internal customers, it would be good to know when the next official release is coming.

**Comment by vmaffione** [comment]
Hi,
  While it is true that some tags have been created in the past (like the v11.1 you are using), we don't plan to have official releases, for the moment being. We only maintain the master branch (so it is a sort of rolling-release), and all bug-fixes and new features go there. This is a workflow that we can sustain.

The master branch, however, is not used to publish unstable/incomplete features, and we don't add incompatibilies with previous versions of the code. So what we publish in master should be stable, it is intended to be usable.

If you are using v11.1, you are for sure missing some features and bug-fixes, and it would be great for us to know if your application/deployment works ok with the current master branch.

**Comment by morphyno** [comment]
Thanks @vmaffione, how often is master synchronized? Do all commits go into the master or there is a process that filters them?

**Comment by emctoo** [comment]
@vmaffione interested in how pull request merged?

**Comment by vmaffione** [comment]
@morphyno, the frequency is not fixed, just depends on what is going on on the development. Bug-fixes go immediately into master, while new features go into master only when complete and sufficiently tested. All commits usually go to master. We try to produce well-shaped, clean commits (and this is what we expect from pull requests), also to allow git-bisect. However, we don't have extremely strong requirements.

@emctoo: Unfortunately we cannot merge pull requests directly through github interface, for the moment (it depends on the way we manage our internal repository). However, you can submit a pull request, and once accepted we can just merge it manually (e.g. using git am).

**Comment by gureedo** [comment]
As I can see master branch is not well tested (see a8054f4) and use of latest master source on production without versioning is very dangerous.

**Comment by vmaffione** [comment]
I'm afraid perfect testing coverage is never possible :)
The netmap subsystems by themselves (e.g. netmap API, native adapters, emulated adapter, pipes, VALE, ptnetmap, etc.) are tested enough, considering the size of the project.

This said, netmap supports almost 40 vanilla kernel versions, plus heaviliy patched kernels (e.g. CentOS). If you combine those with the different NICs we support, netmap subsystems and example netmap applications, you can see that the number of combination is huge. So we must rely on the community to hit version-specific problems (like the one you are pointing at) and report them, so that we can converge to a better codebase.

The releases help to prevent new features to break previous ones, but cannot help with version-specific bugs like a8054f4 , which come from specific combinations that probably we never had the chance to catch. These bugs can only be fixed in a rolling-release fashion.

However, if you are interested, we created a release tag some days ago v11.2
