### ISSUE TITLE
Included bridge example issues with CentOS 7.1 & igb driver

### ISSUE THREAD

**Issue by potahov** [luigirizzo/netmap#175]
I'm using CentOS 7 on a 3.10.0 kernel with patched igb driver. Launching bridge example with parameters "-i netmap:eth0 -i netmap:eth0^" stops the ability to receive small packets from remote machines (however some still work - i.e. for example I'm able to ping the gateway couple switches away and it replies but unable to make a DNS query to it - I see it going out on tcpdump however reply never comes back, same time making a DNS request to a machine on same switch always work and reply is delivered). Could you please give a hint where to look further - as on my understanding using bridge between NIC and host interface should transparently allow all traffic in both directions however it clearly cuts large portions of it somehow.

Thanks!

**Comment by vmaffione** [comment]
Have you put your NIC in promisc mode?

**Comment by potahov** [comment]
I did with a syscall, haven't tried with ifconfig... does it still mater even when I only process packets directed towards this host? May the switch block the traffic somehow?
Maybe there is some other settings that I may miss? I'm adding igb module without any additional parameters (basically insmod igb/igb.ko)

**Comment by vmaffione** [comment]
In order to receive all the Ethernet packets with netmap you must set the card in promisc mode.
There should not be other settings.

Is the log showing something error-like?

To see if the igb patched driver is a problem, can you try to make the same experiment using the original igb driver (so that the emulated/generic adapter is used)?

**Comment by potahov** [comment]
There are no errors in logs however I've tried it with non-patched original kernel driver and it works fine in this case.

**Comment by vmaffione** [comment]
Ok so this is a bug of the igb netmap patch.
Now that you point this out, this was already reported, please check the DETAILS section of LINUX/README.

Are you using the very latest netmap commit in this repo?

If you want to further debug the netmap patched igb driver, you could try to run
````
# ./pkt-gen -i ethX -f rx -X
````
where ethX is your igb interface, so that pkt-gen will dump any packet received with netmap by ethX.

Then you use a packet generator on another machine in the same L2 domain. You can use pkt-gen
on the other machine in this way (no need to patch drivers here), to generate 1 ethernet frame per second
````
# ./pkt-gen -i ethY -f tx -l 200 -R1
````
Then you can change the length (-l option) of the generated frame and check how the packets received on the igb interface ethX depends on the length.

**Comment by potahov** [comment]
Yes, I'm using the very latest commit. I also tried it with patched driver from https://github.com/pavel-odintsov/igb-linux-netmap - getting same results on it as well. Will build another machine to test it further, thanks!

**Comment by potahov** [comment]
I've tried it with two machines - one on igb and another is on ixgbe and it seems that all the packets are able to reach the origin not depending on size. However still when I use it in bridge mode to bridge between NIC and a host stack I'm unable to use nor UDP nor TCP correctly from the host system itself.
Strange thing that ICMP still works (checked with different packet sizes and all are correctly delivered and replied) which makes me think that the issue may be in host stack injection code not the driver itself (however it works with unpatched driver correctly).
May it be specific CentOS issue - could you recommend any other Linux distros to try it with?

**Comment by potahov** [comment]
For example below is a TCP dump for interface put in a bridge mode:
./bridge -i netmap:ens1 -i netmap:ens1^

ICMP packets come from outside and went back successfully. I see those replies on the other side just fine.
15:21:56.886099 IP **source** > **bridged**: ICMP echo request, id 3746, seq 9, length 1258
15:21:56.887136 IP **bridged** > **source**: ICMP echo reply, id 3746, seq 9, length 1258
15:21:57.885860 IP **source** > **bridged**: ICMP echo request, id 3746, seq 10, length 1258
15:21:57.886086 IP **bridged** > **source**: ICMP echo reply, id 3746, seq 10, length 1258


Trying to establish the SSH session however doesn't work. I see SYN coming to the bridged side and it is replying. However on a originating side I only see the packets coming out, replies never come back.
15:19:25.004691 IP **source**.47876 > **bridged**.22: Flags [S], seq 2932951905, win 14600, options [mss 1460,sackOK,TS val 680327 ecr 0,nop,wscale 7], length 0
15:19:25.005145 IP **bridged**.22 > **source**.47876: Flags [S.], seq 3388416562, ack 2932951906, win 29200, options [mss 1460,nop,wscale 9], length 0
15:19:26.003561 IP **source**.47876 > **bridged**.22: Flags [S], seq 2932951905, win 14600, options [mss 1460,sackOK,TS val 681328 ecr 0,nop,wscale 7], length 0
15:19:26.004127 IP **bridged**.22 > **source**.47876: Flags [S.], seq 3388416562, ack 2932951906, win 29200, options [mss 1460,nop,wscale 9], length 0
15:19:27.206106 IP **bridged**.22 > **source**.47876: Flags [S.], seq 3388416562, ack 2932951906, win 29200, options [mss 1460,nop,wscale 9], length 0
...

So the issue is somewhere in **sending** packets back to the network interface

**Comment by potahov** [comment]
what this would be it seems related with CentOS - the same example built on Debian 8 works correctly as expected

**Comment by vmaffione** [comment]
Hi, if you are able to use TCPDUMP it means you are using the unpatched driver, right?
Otherwise you would not be able to do that.

So I guess you abandoned the idea to use the igb patched driver - even if it would be nice if you did the tests I outlined, to check what happens.
On the other machine, since you have ixgbe, you should be able to use the patched driver in your tests.

In any case, even using the unpatched igb driver I think I know what is going on.
In order to use host stack rings properly you have to disable TX checksumming offloading, and disable TSO/UFO/GSO.

````
# ethtool -K ens1 tx off tso off gso off sg off
````
In fact, when using ICMP there is no data checksum, so ping works.
With SSH, however, you are using TCP. Since usually TX checksuming is enabled by default, your kernel won't compute the TCP checksum and assume the driver will do that. With current netmap, however, this is not supported, so the TCP checksum won't be computed, and so the receiving node will drop the packet due to incorrect checksum.

You can check if TX checksum offloading is enabled on an interface:
````
# ethtool -k ens1
````

**Comment by potahov** [comment]
ah, you're right! I completely forgot about tx checksum offloading. I did turn of segmentation offloading but not checksum offloading and that was causing the issue. Turning it off helped.
I am able to see the packets even with patched drivers because I'm bridging them back/from the host stack.
Thanks!

**Comment by vmaffione** [comment]
You're welcome! So if that works I guess we can close this issue.
