### ISSUE TITLE
Understanding rings and packet reordering

### ISSUE THREAD

**Issue by deemru** [luigirizzo/netmap#187]
### How rings work if there is more than one ring?

Trivial:
* a single ring can be represented as a single fifo queue
* straightforward, there is no room for packet reordering on TX and RX side

Difficult:
* how can multiple rings be represented? multiple concurent queues?
* if i put 1 packet on each of 32 rings with marks from 1 to 32, what packet ordering will be on TX side?
* if there is 32 packets with marks from 1 to 32 on RX side and 32 rings with 2 slots on each, what packet ordering will be on rings?

### Understanding rings number

Trivial:
* i can open a vale port according my needs, for example 1 ring with 4096 slots

Difficult:
* why there is always 32 rings on my physical netmap ports?
* what is the reason for this?
* how can i work with 32 rings without packet reordering?
* can i simple use 1 ring on TX and RX side?
* will it be effective?
* or is there a better solution?

**Comment by vmaffione** [comment]
2016-05-26 22:36 GMT+02:00 Dmitrii Pichulin <notifications@github.com>:

> How rings work if there is more than one ring?
>
> Trivial:
>
>    - a single ring can be represented as a single fifo queue
>    - straightforward, there is no room for packet reordering on TX and RX
>    side
>
> Difficult:
>
>    - how can multiple rings be represented? multiple concurent queues?
>    - if i put 1 packet on each of 32 rings with marks from 1 to 32, what
>    packet ordering will be on TX side?
>    - if there is 32 packets with marks from 1 to 32 on RX side and 32
>    rings with 2 slots on each, what packet ordering will be on rings?
>
>
Netmap gives you access to all the NIC rings, that's all. It's not involved
in packet scheduling of any type, it's not its job. The packet ordering on
TX side is decided by the NIC hardware, and you have to check the NIC
manual to know the answer. Usually it's just a round/robin policy, but can
be anything.
For RX side, the NIC hardware decides what packet goes into what queue.
Then you can use netmap to read the packet in the order you wish.

>
>
> Understanding rings number
>
> Trivial:
>
>    - i can open a vale port according my needs, for example 1 ring with
>    4096 slots
>
> Difficult:
>
>    - why there is always 32 rings on my physical netmap ports?
>    - what is the reason for this?
>    - how can i work with 32 rings without packet reordering?
>    - can i simple use 1 ring on TX and RX side?
>    - will it be effective?
>    - or is there a better solution?
>
> VALE ports are just software objects, so there is more flexibility. A
physical NIC typically has the number of queues hardwired, so you cannot
change it.
You can use 1 ring on TX and RX side, it depends on the flags you use at
NIOCREGIF time. In this case you would use NR_REG_ONE_NIC, see the man page
for reference.

Depending on your need could be an effective solution. If you have native
netmap support (e.g ixgbe), one ring is probably enough to saturate the
link at minimum packet size. Otherwise you probably need more rings.


>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/187>
>



-- 
Vincenzo Maffione

**Comment by deemru** [comment]
My appreciation. Understood.
