### ISSUE TITLE
host rings don't receive any traffic?

### ISSUE THREAD

**Issue by rbtcollins** [luigirizzo/netmap#192]
This is perhaps more a FAQ / doc issue - perhaps I'm misunderstanding things but 

```
pkt-gen -i eth0^ -f rxseq -n 20
```

should receive traffic if I start a ping running from the host to another machine..

with current master this doesn't see any traffic - poll is returning 0 on every iteration, and it never gets past 'waiting for initial packets', whereas if I do it on eth0 and throw external traffic at it, it does.

**Comment by vmaffione** [comment]
Three things here:

1. There was a bug in the new defauld txqdisc mode that prevented packets to reach the RX host ring. A fix is already upstream

2. Using -f rxseq does not make sense, since host stack will not transmit packets having the format expected by rxseq. Use -f rx in this case

3. Even with the fix (1), you won't see any packets with
````
# pkt-gen -i eth0^ -f rx
````
Because the hw rings of your device are not in netmap mode, only the host rings are. You can use "eth0*" to also put the hw rings in netmap mode. In this way you should be able to see the packets on the host RX ring.

**Comment by rbtcollins** [comment]
Cool, thanks. I don't think that particular item 3 is documented ? At least, its news to me :). 1 was the issue I had - I ended up with the pkt-gen command as I isolated things looking for a minimal reproduction of what my code was showing.

**Comment by vmaffione** [comment]
Not really documented, AFAIR, right. Do you confirm it is working now, so thati we can close the issue?

**Comment by rbtcollins** [comment]
yes, my code now receives host side and network side packets, as desired ;). Should I file a separate bug for the docs issue?

**Comment by vmaffione** [comment]
yes, please

**Comment by rbtcollins** [comment]
See #193
