### ISSUE TITLE
no error when incompatible offload settings are present

### ISSUE THREAD

**Issue by rbtcollins** [luigirizzo/netmap#195]
netmap silently breaks when checksum offloading is enabled - e.g. bridge netmap:eth0 will fail to forward host->wire tcp traffic (because it outputs with bad checksums).

It would make sense to me that netmap error on open when those features of a nic are enabled, or perhaps it may even be better still to change them on open and restore on close [though I can see that being surprising if folk alter the settings while netmap is running).

See #194 too.

**Comment by vmaffione** [comment]
This is a long standing project decision. Netmap will not change things like device promiscuity, enable/disable tso segementation offloadings, checksum offloadings etc. Doing such things is responsibility of the user application. Also because even if netmap changed them, someone could change it back while netmap is running.

But what we can do is print rate-limited warnings in netmap_transmit() when mbufs requiring offloadings are intercepted to be put on the RX host ring. Those packets have to be dropped, since netmap is not able to handle them.

Actually, netmap has a software implementation of the offloadings (see netmap_offloadings.c), but it is currently only used in VALE switch. Maybe we can make it more generic, so that can be used also by netmap_transmit.

**Comment by rbtcollins** [comment]
Yeah, its fair enough to not change them, but the silent failure is pretty bad :/. May I ask, is it NIC limitations that prevent offloading working with netmap ring inserted packets?

**Comment by vmaffione** [comment]
No, the NIC is able to do the offloadings. But the point of using netmap is that you should not need offloadings, but rely on batching to get good performance.

Also consider that netmap is specially designed to be used in middleboxes applications, which means that you are not the endpoint of a TCP/UDP stream. Offloadings, instead, are really used at endpoints, where the TCP state machine can create large packets with TSO.

The offloadings require many metadata information (see how big the skbuf is). Having those metadata has a considerable overhead, that would hit the performance.

**Comment by vmaffione** [comment]
Done this, will be published soon.
