### ISSUE TITLE
netmap on bridged interface

### ISSUE THREAD

**Issue by deemru** [luigirizzo/netmap#201]
- Does netmap support bridged interfaces?
- If not -- why not, when planned?
- If yes -- why kernel panic (tested on several different patched drivers)?

```
brctl addbr br0 &&
brctl addif br0 eth0 &&
brctl addif br0 eth1 &&
ifconfig eth0 up &&
ifconfig eth1 up &&
ifconfig br0 up
```

```
pkt-gen -i netmap:eth1^ -f rx
```

![image](https://cloud.githubusercontent.com/assets/10706633/17182253/901109ac-542b-11e6-86dc-3adb8578fe45.png)

**Comment by vmaffione** [comment]
Hi,
  This is clearly a bug, thanks for pointing it out. Can you post the full stack trace so that we can see where the fault is happening? Are you using the e1000 patched driver in this test?

Apart from the bug, it's unclear to me why you may want to use netmap on a bridged interface. If you bridge eth0 to br0, it means that you want eth0 to be a port of a software bridge implemented by the linux kernel, which also means that you don't want to use netmap on eth0. On the contrary, it would make sense to use netmap (e.g. pkt-gen) on br0, and you should be able to do it.
What to you want to achieve, exactly?

**Comment by deemru** [comment]
Full stack is a pain, cause i am not familiar with linux kernel debugging, but this bug appears on every Debian which i tried with patched e1000 and ixgbe drivers at least (very easy to reproduce).

I am developing [multithreaded ESP-tunnel](https://github.com/deemru/netmap/blob/master/examples/esptun.c) based on netmap framework and one approach is to pass a hard MTU stuff (fragmenting/defragmenting and `clamp-mss-to-pmtu`) to an OS, and if we stand between `netmap:ethX^` and `netmap:ethX` then packets will be automatically length-ready for ESP-tunnel overhead.

**Comment by vmaffione** [comment]
I've found the bug, I will publish a fix soon. In the meanwhile, from your code and explanation it seems that you want your program (https://github.com/deemru/netmap/blob/master/examples/esptun.c, which is an extension of bridge.c) to be the bridge. So you don't have to create an in kernel bridge, you just have forward the packets in your application.

**Comment by deemru** [comment]
> I've found the bug, I will publish a fix soon

Great news!

> So you don't have to create an in kernel bridge, you just have forward the packets in your application.

It is one of approaches to be more flexible.

**Comment by vmaffione** [comment]
I've found the bug, I will publish a fix soon. In the meanwhile, from your code and explanation it seems that you want your program (https://github.com/deemru/netmap/blob/master/examples/esptun.c, which is an extension of bridge.) to be the bridge. So you don't have to create an in kernel bridge, you just have forward the packets in your application.

**Comment by vmaffione** [comment]
1. You cannot netmap_open() a NIC with unpatched driver if the NIC is attached to a bridge. This is because of the way unpatched driver support (emulated netmap) is implemented.
2. With a patched driver it should work (once you have the bugfix), but you are bypassing the bridge anyway, so it does not make sense to bridge the NIC to br0 in the first place.

So in conclusion I would say that opening a network interface with netmap and bridging a network interface to software bridge are mutually exclusive.

**Comment by deemru** [comment]
Let me explain this case:
- We have a few common LANs
- We want to bridge them with encryption over a WAN
- This encapsulation needs some overhead
- So we need packets smaller than the WAN MTU minus the encapsulation overhead
- We can leave the MTU question to the network administrator (incomplete solution)
- We can manage fragmentation and TCP MSS questions by ourself (hard solution)
- Or we can use a kernel bridge to do the job (easy solution)
- We set a smaller MTU on the WAN side and bridge it with the LAN
- Then we break the WAN interface with its IP stack (with netmap)
- At this point we have fully prepaired packets at the WAN IP stack side
- And the WAN interface with the real MTU on the other side
- So we run our tunnel between the WAN IP stack and the WAN interface

Base configuration:
LAN1 <> WAN1 <> WAN2 <> LAN2

Incomplete solution:
LAN1 <> LAN1* < ESPTUN > WAN1 <> WAN2 < ESPTUN > LAN2* <> LAN2

hard solution:
LAN1 < ESPTUN > WAN1 <> WAN2 < ESPTUN > LAN2

easy solution:
LAN1 <> WAN1* < ESPTUN > WAN1 <> WAN2 < ESPTUN > WAN2* <> LAN2

--
_* - means smaller MTU_

**Comment by vmaffione** [comment]
Ok, then the way to go is the following, where you would set a smaller MTU on the tap0 TAP interface. Note that you don't need to use host rings (e.g. eth0^ or eth0*) to do this.

![untitled presentation](https://cloud.githubusercontent.com/assets/4920001/17246403/125709b4-558c-11e6-9fe2-9a6fd946d1f9.png)

**Comment by vmaffione** [comment]
Or, maybe better with the veths (using the unpatched driver).
![untitled presentation](https://cloud.githubusercontent.com/assets/4920001/17246461/81d98d16-558c-11e6-8013-1b89770aa691.png)

**Comment by deemru** [comment]
Thank you for your solutions, we will check them for best performance.

**Comment by vmaffione** [comment]
Note that in the first solution you must read from the TAP using read() and write(), not netmap (always for the same reason, tap0 is bridged, so you cannot use netmap). While in the second you can use netmap on veth1.

**Comment by vmaffione** [comment]
I will close this since the fix has been published. Should the problem still be there please reopen this.
