### ISSUE TITLE
Name not recognized, not an error

### ISSUE THREAD

**Issue by apeace** [luigirizzo/netmap#208]
Hi there, thanks for the great library!

I made the mistake of calling `nm_open` without prepending `netmap:` to my interface name. I realized my mistake eventually, but I was surprised there was no error reported for this.

[This if block](https://github.com/luigirizzo/netmap/blob/05c680892969c9a7f9cbd35c52e18a4170a55e9d/sys/net/netmap_user.h#L627) appears to intentionally ignore that case. And yet, the result returned is a null pointer.

From my perspective, I'd never want a null pointer returned without receiving an error message. A few lines below that if block, there is another one which provides an error if the interface name is too long. I think something like that would be more useful.

I apologize if I've overlooked a reason that it currently works this way!

**Comment by vmaffione** [comment]
Hi,
That's a good question,actually. No error is reported because that case is not considered to be an error (errno=0). The reason of this api behaviour is related to libpcap,which was one of the first software that gained netmap support. Libpcap can use different back ends to do packet capture (raw sockets, net map, etc..), and tries to open one of them, until one of them succeeds. Netmap is selected if the ifname satisfies those conditions, but if the conditions are not satisfied then no error is reported so that libpcap can go ahead and try another back end.

**Comment by c4milo** [comment]
I see, we are trying to use netmap without libpcap and this detail trickled us for a bit.

**Comment by apeace** [comment]
@vmaffione do you think it would be worth leaving this issue open, and potentially fixing this behavior in libpcap? That way netmap can have the more intuitive behavior of reporting an error in this case.

(I wouldn't have time to patch libpcap myself, but perhaps someone determined may see this issue someday and take it on)

**Comment by vmaffione** [comment]
I can see your point, but this API has been there for a long time, and probably changing it would cause more harm than benefits. Not only libpcap, but all the programs using nm_open() would need to be modified. And we do track all of them. By the way, what error code would you suggest? EINVAL?

In any case, we need Luigi's opinion here. You could try to send him an email (with me in CC), and start a discussion.

**Comment by c4milo** [comment]
@vmaffione, another `goto fail` may make sense and be consistent.

**Comment by vmaffione** [comment]
It is a change of API, we don't want to disrupt existing applications which rely on errno==0 in this case.
