### ISSUE TITLE
Processing packets in batch?

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#216]
I know that Netmap processes packets in batch, what I want to know is that is it possible to process packets in batch in the userspace application? Retrieving all the packets from the queue at once, but also preserving the length information of all the packets?

**Comment by vmaffione** [comment]
Yes, this is what netmap is intended for.

**Comment by Linerd** [comment]
Maybe my question is not clear enough(Or more likely I still need some explanations...), what I am asking is(as I see in the pkt-gen.c and bridge.c examples), is there any way to process the packets without iterating over the slots? In the two examples, there is still a loop iterating every slot, accessing the slot->len and the corresponding buffer according to the id. Is there a way to process the slots in batch? Otherwise I don't see how this is batching?

**Comment by vmaffione** [comment]
The batching refers to the amortization of system calls, hardware register writes and interrupts. pkt-gen, bridge and the others example do process the packets in batches in this sense.
What you are asking for would probably require a quantum computer ;) Or maybe a GPU which can do things in parallel.

**Comment by dvatsav** [comment]
@vmaffione I tried something similar with a GPU, but could not get it to work properly (I modified the bridge.c application for my use case). I'm using an SOC that has unified memory for the GPU and CPU. Is there anyway I can map the userspace netmap buffers to lie in this unified memory so that I can access them directly from the GPU?
As of now I have to copy all the packets from the rxring to a buffer that I have created in the unified memory, and then process them in parallel on the GPU. 
I'm facing issues with this though. When I iterate through the packets one by one and process them separately (similar to what the [bridge](https://github.com/luigirizzo/netmap/blob/master/apps/bridge/bridge.c) does), I always get ~100 packets on the rxring (got this count using nm_ring_space).
But when I try to process them as a batch ([example](https://pastebin.com/PqRtSDWw), I only get 1 or 2 packets on the rxring each time, and this leads to a huge performance drop.

Is there any other way for me to batch process effectively while still using a GPU?

Ubuntu 18.04, kernel - 4.15.0-65-generic.

**Comment by vmaffione** [comment]
It sounds like you should use the extmem feature to map netmap buffers and rings directly to the GPU-accessible memory.
Take a look at https://github.com/luigirizzo/netmap/issues/545
and https://github.com/luigirizzo/netmap/blob/master/utils/extmem-example.c
