### ISSUE TITLE
can't receive anything - Windows

### ISSUE THREAD

**Issue by psechenov** [luigirizzo/netmap#243]
Hello Alessio,

Using patches form this issue (https://github.com/luigirizzo/netmap/issues/234) I managed to compile netmap on windows and get it running successfully:

![netmap_loading](https://cloud.githubusercontent.com/assets/17339835/19619712/6861967a-9822-11e6-8995-20f7a7ddd482.png)
Installing service on adapter is also ok. Windows is in Test mode.

But I stumbled into the problem while getting a pkg-gen example running in receiving mode. It actually works, but i didn't manage to receive any package with it:

![netmap_receiving](https://cloud.githubusercontent.com/assets/17339835/19619714/686296ba-9822-11e6-8bcf-2f1040595e5f.png)

You can see that poll call output is always 1, but It doesn't receive anything because 
`if (nm_ring_empty(rxring))`
this condition is always true. As i understand netmap rings are empty (there is only one actually), but it's not getting filled. Could you give me some clue on what i am doing wrong? My final goal is getting netmap running on windows on receiving mode and receive everything that comes to the adapter.

Some additional information: 
- Wareshark receives something on the interface i use for netmap, but netmap doesn't. 
- My ipconfig output:
  ![ip_config](https://cloud.githubusercontent.com/assets/17339835/19619713/686191c0-9822-11e6-8577-c8c7903a2a8e.png)
- Interface is in promiscuous mode:
  ![adapter_promiscuous](https://cloud.githubusercontent.com/assets/17339835/19619715/68632f1c-9822-11e6-8bd9-395e16cdf63f.png)

Thank you in advance,
Pavel

**Comment by vmaffione** [comment]
Alessio will know better than me for sure, but I have two questions:
- have you set promiscuous mode inside windows? I'm not sure allowing it in VirtualBox really does the job.
- does pkt-gen over VALE work?

**Comment by Alessio-Faina** [comment]
Hi @psechenov ,

first thing I remember working with VMs (I was using HyperV but I think this may be the same issue) is that you need to specify the sender and destination mac address on the sender side. If you don't do that you won't be able to see any packet on the receiver side.

Let me know if this makes any difference

**Comment by psechenov** [comment]
Hi Vincenzo,

I appreciate any help, thank you!

1. have you set promiscuous mode inside windows? I'm not sure allowing it in VirtualBox really does the job.

Well, I use Intel PRO/1000 MT Desktop and it seems that it supports promiscuous mode, that can be turned on by OS (http://www.intel.com/content/www/us/en/support/network-and-i-o/ethernet-products/000007255.html). But i didn't find any way to set this option up into OS. netsh bridge show adapter command shows nothing.
Though wareshark can set promiscuous option up.

2. does pkt-gen over VALE work?

Seems it doesn't
pkt-gen-b -i vale1:a -f tx
pkt-gen-b -i vale1:b -f rx
![netmap_vale](https://cloud.githubusercontent.com/assets/17339835/19641514/dc9f2e16-9995-11e6-9d8f-0f1cf6758969.png)

**Comment by psechenov** [comment]
Hi Alessio,
Thank you for your attention to the topic!

Actually I've tried something like this, but OS failed. I'll dig deeper into the problem and certainly let you know about the results.

**Comment by psechenov** [comment]
Hi @Alessio-Faina,

I've tried to specify source and destination mac address on sender part locally over VALE.
Doesn't make any difference.
![sender_reciever_mac_source_dest](https://cloud.githubusercontent.com/assets/17339835/19654678/341bf65a-99ce-11e6-8f61-1cdc5b3855c4.png)

And just to be clear. We are developing the driver with netmap support (linux as well as windows) for video capture card. And the main thing is to provide fast receiving part. In this case i wouldn't like to specify sender at all. Instead I'd like to receive everything that comes to the adapter. I would be quite close to our case. As I understand packages that Wireshark receives has everything it takes including mac src/dst addresses.

Could it be possible for me to use netmap this way or I misunderstand?

Thank you!

**Comment by vmaffione** [comment]
Yes, receiving anything it comes from an Ethernet adapter (independently on source/dest MAC address, so packet capture for traffic monitoring) is one of the many things you can do with netmap. Point here is that something is broken in the windows support. You could try to enable "netmap_verbose" to see something in the log (but I don't know how to do that on Windows and where to see the logs).

**Comment by psechenov** [comment]
@vmaffione, thank you for your answer. I'll try all of this and let you know.

**Comment by psechenov** [comment]
Hi @vmaffione, @Alessio-Faina 
I tried the following test locally:
pkt-gen-b -i netmap:eth6 -f tx -S 08:00:27:43:FD:AF -D 08:00:27:43:FD:AF
pkt-gen-b -i netmap:eth6 -f rx

still nothing received.

@Alessio-Faina, maybe testing locally on one VM is not enough and i should try two VMs. If so what src/dst ip address should i pass on receiving/sender parts (it's little bit confusing) ? Please let me know. 

I will continue to investigate the Windows part. If you know concretely what's the problem on Windows please provide me with that. We will consider repairing the broken parts.

Thank you.

**Comment by vmaffione** [comment]
Hi,
  The first step is to find why pkt-gen across VALE does not work (without specifying any -S or -D, just broadcast packets, a sender and a receiver).

If this basic test does not work it means that something fundamental is broken in the Windows port. All the other things are just a consequence, so it does not matter how many VMs you try, wether you try on physical ports, or if you specify src/mac addresses.

Rather than using current master, could you give a try to this old commit 2da6fb0a677544987f032865ba8adb0b893d4bd6, which is the last commit from Alessio? It's an old netmap version, but at least it dates back to the period when the Windows porting was being actively developed. You should also try both pkt-gen and pkt-gen-b

````
# pkt-gen -i vale:1 -f rx
# pkt-gen -i vale:2 -f tx
````

**Comment by psechenov** [comment]
Thank you, @vmaffione! I'll try all of it and write back.

**Comment by psechenov** [comment]
Hi @vmaffione, I tried everything you proposed. None of that works on VirtualBox - nor pure VALE connection nor commit you specified nor pkt-gen-b and pkt-gen. Then i tried the same on Hyper-V and it turns out that it works. On Hyper-V everything works just fine, even receiving from network adapter. 

Now I'm gonna give a try to deploy everything on physical device. If everything is fine I'll continue working under Hyper-V just for the sake of debugging and developing.

**Comment by vmaffione** [comment]
That's interesting news, thanks for testing! So if I understand correctly also the current netmap master works inside an HyperV virtual machine?
And you are going to try netmap on a physical Windows machine, I guess.

It is really weird that it does not work in Virtual Box, and it is unlikely to be a Virtual Box bug...

**Comment by psechenov** [comment]
I haven't tested master but I think it is gonna work. I've tested this commit 2da6fb0 you specified above.
I you need/would like I can try master on Hyper-V. Just let me know. 


>  So if I understand correctly also the current netmap master works inside an HyperV virtual machine?
Exactly. Because it's rather important for us to get netmap running on physical device. 
And yes, it's quite strange that VM matters..

Let me ask you several quiestions about our further perspectives.
1) Should we use special network card that netmap has support to on Windows?
2) As I understand speed on windows on receiving part is restricted by the native driver. Is that possible to modify the driver to increase the speed (the similar way it's required for linux) ?
And as I understand nm-dis filter doesn't need any changes in the scheme because it just goes to native driver to get packages and put them in the netmap rings. Please correct me if i'm wrong.

**Comment by vmaffione** [comment]
Thanks, it would be great if you could give a try to current master inside Hyper-V and on the physical machine, with both VALE tests and NIC tests.

Yes, both receive and transmit performance is limited by the original Windows driver and the Windows network stack. The current windows port uses the "generic" (emulated) netmap adapters, which relies on NDIS hooks to inject packets to the unmodified driver and the network stack, in order to make the driver interact with the netmap rings (as you are saying).

In theory, it should be possible to modify/exend existing Windows drivers (e.g. the ones for Intel NICs) to add native netmap support (like it happens for Linux/FreeBSD). In general, the amount of code to write is about ~500 lines, so not so much. Of course you need the Windows NIC drivers to be open source, and I don't know if this is the case for the 10Gbit you may have (Intel? Mellanox? Broadcom?).

Unfortunately, we don't have expertise on Windows drivers or Windows network stack, so we don't have plans in that direction for now. However, if you would like to contribute in this direction, maybe porting an Intel 10Gbit driver to netmap it would be really great, and we could give you some directions related to the interactions with netmap.

**Comment by phoenix1796** [comment]
*bump*
I am working with netmap in Windows , and would like to know if your solution worked ?
@psechenov 
&
Can anyone please leave some instructions on how to set a Win7x64 OS's NIC in promiscuous mode without using the bridge component ? (I seem to be amiss here .... (https://github.com/luigirizzo/netmap/issues/335)
