### ISSUE TITLE
Communication between network namespaces with Vale

### ISSUE THREAD

**Issue by daehyeok-kim** [luigirizzo/netmap#247]
Hi all,

I am trying to setup a virtual network consisting of two hosts in different network namespaces connected to Vale. It looks like this:
h1[h1eth0]------[s1eth1]Vale0[s1eth2]------[h2eth0]h2
Note that [...] indicates ports on each host and Vale. 

After loading netmap.ko and patched veth.ko module, I setup the above network configuration with the following commands (in Ubuntu 14.04; 3.19.0-73-generic):
- Create host namespaces 
ip netns add h1 
ip netns add h2 

- Create links
ip link add h1eth0 type veth peer name s1eth1 
ip link add h2eth0 type veth peer name s1eth2 
ip link set h1eth0 netns h1 
ip link set h2eth0 netns h2

- Set Vale ports 
./vale-ctl -a vale0:s1eth1
./vale-ctl -a vale0:s1eth2
and confirmed that 
617.352138 bdg_ctl [148] bridge:0 port:0 vale0:s1eth1
617.352188 bdg_ctl [148] bridge:0 port:1 vale0:s1eth2

- Configure network
ip netns exec h1 ifconfig h1eth0 10.1 
ip netns exec h1 ifconfig lo up 
ip netns exec h2 ifconfig h2eth0 10.2 
ip netns exec h1 ifconfig lo up

When I tried to ping from h1 (10.0.0.1) to h2 (10.0.0.2), I got the Destination Host Unreachable message.

Did I miss something to enable the above topology? 
Thank you.

**Comment by vmaffione** [comment]
Hi,
  There is nothing wrong in your setup. The problem is that veth native adapter is still a prototype, so it only works when both the end of a veth pair are in netmap mode. So in this case s1eth1 is in netmap mode (as it is attached to VALE), while its pair h1eth0 is not in netmap mode (you use the network stack: ICMP, etc). The other pair is similar. If you use the emulated/generic adapter (e.g. no veth.ko patched driver) it will work.

But even if we supported this, you would not have the performance advantages of netmap, because the network stack in the h1/h2 namespaces would be the bottleneck. This is why the prototype has not progressed in that direction: we feel there would not be advantage w.r.t using standard in-kernel bridge (brctl). A different thing is if you want to use netmap applications in h1 and h2. In that case both the ends of the pairs would be in netmap mode and you would take advantage of netmap as you can do operations in batches, benefit of memory preallocation, etc.

The question is, what do you want to achieve?

**Comment by daehyeok-kim** [comment]
Hi, 
Thanks for your comment.

What I want to achieve is to enable a communication between two processes (virtual hosts) in different namespaces without going through the kernel network stack and use Vale as a virtual switch. I want to see how much performance improvement we can get in this setting (i.e., virtual network). 

I think the problem was that I didn't use netmap application to send/receive packets. 
Now, I can transmit and receive packets from h1 to h2 using pkt-gen with the following command:
ip netns exec h1 ./pkt-gen -i h1eth0 -f tx -l 60 -w 5
ip netns exec h2 ./pkt-gen -i h2eth0 -f rx

However, the transmission rate is quiet low:
16.802 Mpps (16.819 Mpkts 8.073 Gbps in 1001046 usec)

When I ran the pkt-gen on native nic (e1000e), I got the rate around 70 Gbps.
Is this a limitation of veth interface?

Thank you.

**Comment by vmaffione** [comment]
I don't think 16 millions packets per second can be defined as "low transmission rate" :)
If you are interested in bytes throughput you can use larger packets (e.g. -l 1500 in pkg-gen command line).

The driver e1000e is for 1Gbps NIC, so It's definitely not possible that you got 70 Gbps, it must be something wrong in your setup.

**Comment by daehyeok-kim** [comment]
Oh I misinterpreted the message :) Thanks for your help.
