### ISSUE TITLE
can an interface remain in netmap mode indefinitely?

### ISSUE THREAD

**Issue by fklassen** [luigirizzo/netmap#279]
I am dealing with a [netmap feature request in Tcpreplay](https://github.com/appneta/tcpreplay/issues/250). Basically, my users want to stop the program without switching netmap back to normal, then continue to use it next time to program starts.

Is there a way I can not reset the netmap interface between instances?

**Comment by vmaffione** [comment]
Hi,
  An interface is in netmap mode if and only if there is at least a program running with an open netmap file descriptor bound to some of the interface's rings. So the only thing you can do is to run a background daemon that nm_open the interface (binding all the rings) and sleeps forever, never accessing the rings.

**Comment by fklassen** [comment]
Thanks. I was able to control this before version 10. It appears that this capability has gone away.

Will close this issue. Please let me know if this control ever comes back.

**Comment by vmaffione** [comment]
I may be wrong but I don't remember this capability, maybe it was a bug on a very old version of the code...

**Comment by fklassen** [comment]
I'll reopen this issue, and make it into a request. 

I found the following code, which essentially allows a user to turn netmap on/off via ioctl. As you can see, it work prior to version 10.

https://github.com/appneta/tcpreplay/blob/master/src/common/netmap.c#L529
I understand that current behaviour does not allow a user to keep the interface open after shutting down netmap. Also, it open and resets the interface when it is open. Can these behaviours become default, and add ioctl calls that will allow me to override it?

Of course I would also need a version bump so I can detect the version. I want many versions of netmap to work with Tcpreplay.

Thanks, Fred.

**Comment by vmaffione** [comment]
There is no "shutting down netmap", the fact that an interface is open in netmap mode just means that there is some open file descriptor on which REGIF has been called. When there are no such file descriptors, the interface goes again back to normal mode.

That piece of code is not valid anymore, right, UNREGIF was removed (years ago) for safety reasons: we use reference counting to understand when the netmap data structures (rings, slots, buffers, etc) can be freed. But we don't want to rely on the application to explicitely call "UNREGIF", because the application can crash or terminate without calling that; if this happens, the netmap data structures are not freed (as reference count does not go to 0), and the machine would not be even able to shutdown, as it would not be able to remove the netmap module.

As I already suggested, you can get what you want (interface always in netmap mode), by writing a very simple background daemon that just nm_opens() the interface and sleeps forever. You can start that daemon at boot, and then play with tcpreplay as you wish, starting and stopping it at will.
