### ISSUE TITLE
HostStack Rings

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#283]
It seems we can't use hoststack ring with multiple threads, however in my scenario, I'd like to use one thread (with one CPU via affinitty) per NIC queue and once I've checked the packets, forward them to host stack and so forth.

My question is, what would be the possibility, to also allow host stack to work by rings the same way as the NIC ? Is there such possibility ? This way it wouldn't require locking.

I'm doing proper locking, but the problem is I've noticed that poll() call, will also touch NIC rings via netmap (Am I wrong on this maybe ?), and then, I believe, calling poll() without locks is what might be causing the corruption in HostStack rx/tx rings, the question is, when I use a simple lock around the poll() call, the whole thing stops to work, like in a deadlock, and it doesn't leaves this, so what could be the alternative ? I guess none right ?

**Comment by vmaffione** [comment]
Host rings ar not meant to be part of the "fast-path", since converting buffers back and forth between netmap buffer and skbuff/mbuff (plus the syscall and copy for socket application) is expensive anyway.
It is not possible to have multiple host RX rings nor multiple host TX rings, though netmap could potentially be extended to support this.

In kernel-space, kernel-owned portions of the rings are protected by locks, so corruption cannot happen there. Corruption can happen if your application does lockless concurrent access to the rings.
poll() can (and should) be called without any locks, provided you respect the netmap API (user-owned parts of the rings, cur, head, tail, etc.).

If you are using NS_FORWARD on RX host ring, then kernel-space will access the hardware TX rings under the hood (chaning cur and head), and so you shouldn't use hw TX rings from the other threads.
I would say, it is better not to use NS_FORWARD on host RX ring.

**Comment by Fr3DBr** [comment]
I'm using bridge example, so not using NS_FORWARD so far. Although, I plan to use the host-ring at the same speed as it can handle by default, but I need a way to drop packets before it hits the host (with netmap) at 14 Mpps rate, get it ?

**Comment by Fr3DBr** [comment]
Since we're discussing here: https://github.com/luigirizzo/netmap/issues/281 I'm closing this one, thanks. 👍
