### ISSUE TITLE
Native netmap support for veth interfaces to enable fast container networking

### ISSUE THREAD

**Issue by vmaffione** [luigirizzo/netmap#293]
Fix and complete native support for Linux "veth" devices, in order to support netmap applications running in containers (e.g. LXC containers), or simply in different Linux network namespaces.

The "host-side" veth of each veth pair can then attached to the VALE switch, to support high performance inter-container switching. Or, the two ends of the veth can be given to different containers/namespaces, to implement a point-to-point link between two containers.

In any case, a veth pair in netmap mode behaves in the same way a pair of netmap pipes does, achieving 30-40 Mpps or more.

**Comment by vmaffione** [comment]
Feature implemented.

**Comment by Linerd** [comment]
Could you point me to the correct setup to test out this feature? @vmaffione

**Comment by vmaffione** [comment]
You need to compile netmap with `--kernel-sources` pointing at the sources for your running kernel, so that the patched `veth.ko` module is built. Once you replace the stock `veth.ko` with the modified one, you can create a couple of veths (e.g. using the `ip link` command), bring them up, and run pkt-gen on both ends:
````
# pkt-gen  -i veth0 -f rx
# pkt-gen -i veth1 -f tx
````

**Comment by Linerd** [comment]
@vmaffione And is it possible attach two veth ports to a VALE switch and let two containers communicate with each other?
BTW, is there a way to control the traffic inside VALE to go from a specified port to another? It is said on the website that it works as a learning switch, but I am not entirely sure that's accomplished

**Comment by vmaffione** [comment]
You can either attach the veth ports to a VALE switch to create a virtual LAN of containers. Or simply give one end of the veth to one container and the other end to another container (no VALE switch in between), so that you have a peer-to-peer link.
VALE by default behaves as a simple L2 learning switch.

**Comment by giuseppelettieri** [comment]
Pipes and patched veths are basically the same, but there is no API to move pipes to different namespaces. I don't feel there is any need for it, either, since veths already do the job. What we might need, instead, are non-zero-copy pipes/veths, since sharing memory should always be optional.

As for VALE, it makes perfectly sense to create several persistent VALE ports, attach them to a VALE switch and then move each port to a different namespace, thereby connecting the namespaces in much the same way as VALE-connected virtual machines. It is not currently supported only because nobody has tested it. If you feel adventurous, you can try to apply this patch and share your experience:

```
diff --git a/LINUX/netmap_linux.c b/LINUX/netmap_linux.c
index b14e899f..9077b6e9 100644
--- a/LINUX/netmap_linux.c
+++ b/LINUX/netmap_linux.c
@@ -2230,7 +2230,6 @@ nm_os_vi_persist(const char *name, struct ifnet **ret)
                goto err_put;
        }
        dev_net_set(ifp, &init_net);
-       ifp->features |= NETIF_F_NETNS_LOCAL; /* just for safety */
        ifp->dev.driver = &linux_dummy_drv;
        error = register_netdev(ifp);
        if (error < 0) {
```
