### ISSUE TITLE
Using emulated netmap mode with VLANs

### ISSUE THREAD

**Issue by ghgngpw** [luigirizzo/netmap#302]
Hi guys,

Does emulated netmap mode support VLAN tagged frames? What I tried is to run netmap on an interface where all incoming traffic are VLAN-tagged frames. Since the interface's driver is not one of the supported one, I assume emulated netmap mode will be used. Let's call the interface name "eth0". When I run (test_nm "netmap:eth0" r) I am not able to see any of the ingress VLAN-tagged frames. But doing (test_nm "netmap:eth0.100" r) allows me to see all the VLAN100 tagged frames. If untagged frames are sent to eth0, then (test_nm "netmap:eth0" r) shows the frames with no problem.

Is this expected behaviour? Is there anyway I can have netmap running on "eth0" interface and still see all those VLAN-tagged frames?

Thank you!

**Comment by vmaffione** [comment]
Hi,
  As you have seen netmap emulated mode works basically on any software or hardware network interface. In this case, eth0.100 is just a software interface.

However, it does not really make sense to use vlan interfaces with netmap, you should just read from the real interface eth0 and manage the VLAN tags in your application. This is true specially for supported drivers (e.g. ixgbe), since you can run at full netmap speed (native mode) only with the real interface eth0, and you simply can't t do that with VLAN interfaces.

If your NIC driver is not supported (which driver are you using exactly?), then emulated mode is used anyway also for the real interface. But since the VLAN dispatching is done before netmap emulated mode intercepts the packet received from the driver, there is no way to do what you need if you have the VLAN interfaces (e.g. eth0.100) created. I guess if you remove the VLAN interfaces you can then nm_open() netmap:eth0 and see the tagged frames.

**Comment by ghgngpw** [comment]
Thank you for such a quick reply! Yes, I understand using netmap on VLAN interfaces does not make much sense and it is not my intention to do that. My intended use of netmap is to intercept all frames ingress on an interface such as "eth0", manipulate (e.g. edit/remove/duplicate) some of the frames and then send those frames up the host stack. The goal is to make the apps/services on the system unaware of such interruption. VLAN interfaces in this case are critical to some routing applications which means removing them would be out of the questions. And yes, I did try to remove the VLAN interfaces and I can start seeing VLAN-tagged frames ingress on eth0.

Seems like I'd need to attack this from a different angle.

Thank you.

**Comment by vmaffione** [comment]
I see. The best approach would be to have native netmap support for the NIC you are using.

Or you need some workaround like attaching eth0 to a bridge, a TAP interface to the same bridge, and create the VLANs on the TAP rather than creating them on eth0.

**Comment by ghgngpw** [comment]
Your TAP interface idea sounds very promising and definitely worth exploring. Although having native netmap support on NIC would be ideal but probably not easy since we're dealing with a good number of different embedded system and ethernet drivers.

**Comment by vmaffione** [comment]
Or probably you can do the same workkaaround with a vale switch in place of the in kernel bridge and a persistent vale port rather than a tap. The tap and the in kernel bridge are going to be a bottleneck for sure.
