### ISSUE TITLE
Recommended NICs

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#310]
Hi, guys.

Currently I'm using Intel 82599 NICs in my environment, I would like to know if you indicate any other 10G NICs in other to obtain better results ? What I mean is that due to the way the cache alignment work with 82599, there are certain packet sizes that won't go linerate due to added padding necessary to align these packets, are there any other NICs that wouldn't suffer from this effect that you know of ?

**Comment by jmtilli** [comment]
You could use i40e. They are available in X710 (X is ten in roman numerals) 10Gbps variant and XL710 (XL is forty in roman numerals) 40Gbps variant. I obtained 98.5% of 40Gbps line rate using a mixture of 64-byte long (4 bytes over the minimum size, I think) and 1514-byte long packets. The packet length here doesn't include CRC. Is 98.5% of line rate enough for you?

I'm not sure if the cache alignment issue is there with i40e, but I am very satisfied with the performance.

Honestly, I don't see why anybody would choose 10GbE NIC these days for direct connections, as 40GbE is not much more expensive. For switched installations I can see why somebody would like to use 10GbE due to the high cost of 40GbE switches.

The i40e X710 card is available with 4 ports, so if you choose this 4-port variant, you shouldn't run out of ports.

I don't think there is any other supported 10GbE card than i40e and ixgbe.
