### ISSUE TITLE
How to avoid TX packet reordering?

### ISSUE THREAD

**Issue by asb72** [luigirizzo/netmap#341]
How can I get the same ordered sequence of packets in the wire, as it was sent to the netmap slots?
There may be some solution for i40e.

**Comment by vmaffione** [comment]
The packets are already transmitted on the wire in the same order they were submitted to the netmap slot.

**Comment by asb72** [comment]
Thank you. 
Yes it's true, the problem really does appear after enabling the processing of double vans, I rechecked.

Is there a normal solution for i40e with RSS for traffic with double vlan tags?

**Comment by vmaffione** [comment]
Netmap does not introduce any reordering, neither or transmit or receive side.
I don't know if your NIC hardware does reordering when double tagged packets are used, but if it does this is something that you should probably be able to configure following to the documentation of your NIC.

In the meanwhile I'll close this since it's unrelated to netmap.
