### ISSUE TITLE
When I run pkt-gen the host becomes unreachable

### ISSUE THREAD

**Issue by SviMik** [luigirizzo/netmap#359]
I have successfully compiled netmap under CentOS 6 with 4.12.10 kernel (although I had to use --no-ext-drivers=e1000e,igb,i40e because the downloaded version of these drivers failed to compile).

The pkt-gen apparently works both for sending and receiving (I can observe the emitted packets on another machine with tcpdump, and also I can see some number of packets received when I run it in rx mode).

The main problem is that while pkt-gen is working, it takes the adapter into exclusive use, while the host stack can not send/receive packets anymore until the pkt-gen is killed.

The question is:
Is it expected behavior or not? I have read the readme and the website, and still have no idea how it is expected to behavior. From the site and presentation I see that "each card in netmap mode exposes two additional rings that connect to the host stack". But either it doesn't work, wasn't enabled (how?) or I completely misunderstand the sentence.

What I expect:
Being able to run programs like pkt-gen without disturbing the existing communications the server does with the same network adapter. I mean, I have a remote server with a single network card, and I'd like to be able to communicate with the said server via ssh while developing and running my own applications interfacing with the same network adapter. Is it possible?

**Comment by vmaffione** [comment]
To compile the missing driver you could try go ./configure netmap to use the drivers from the kernel sources of your running kernel (add --kernel-sources=/path/to/ksrc).

What you see with pkt-gen, or any netmap application, is the expected behaviour. Netmap steals the NIC from the OS network stack, which is not able to send/receive packet anymore, unless a netmap application uses the host rings to explicitely and selectively restore the connectivity (From netmap man page, 'While a NIC is in netmap mode, the OS will still believe the interface is up and running.  OS-generated packets for that NIC end up into a netmap ring, and another ring is used to send packets into the OS network stack.')
Some useful resources are the introductory slides available here https://github.com/vmaffione/netmap-tutorial, and the netmap man page (man netmap).

What you want to do is definitely possible, and it is exactly the reason why host rings exist. You can have a netmap application transmitting/receiving to/from the NIC in netmap mode, and using the host rings to let only the SSH traffic pass through. But this cannot happen automatically, you must implement this logic explicitely in your netmap application (e.g. when you receive a packet which is IP+TCP at port 22, forward it to the host TX ring, and the other way around).

**Comment by SviMik** [comment]
Thank you for your reply! I suggest adding a warning into LINUX/README, after the line
"sudo pkt-gen -i eth0 -f rx # act as a receiver"
add something like
"Warning: if you are connected to the server remotely via the same interface, you will not be able to communicate with the server after running this command!"

>you must implement this logic explicitely in your netmap application
Now I got the idea. But what about performance? Will the performance of host-stack applications remain the same, or my application will slow it down being an additional step between network adapter and the host stack? Is it good idea to use netmap if only 50% of the traffic is going to be processed by my application, and the rest will go to the host stack?

**Comment by SviMik** [comment]
>Some useful resources are the introductory slides available here https://github.com/vmaffione/netmap-tutorial

Great tutorial, especially I liked the intro.pdf. It could be placed to the main repo, or a link could be thrown into README, so other people could find it too.

As I understand, only one application can open eth0 at the same time?
(Although, for some reason, pkt-gen did not complain when I launched it twice with the same interface. How did it work? Need some explanation, because it doesn't make any sense)

So, let's say I want to write two completely different applications (let's imagine something like DNS server and IPTV streaming server). The machine is something simple with just a single network adapter - eth0. There are also a web server, sshd, and other things I decide to leave up to the host stack. The machine wants an internet access too, so basically I need to forward any leftover packets to the host. As I understand, I need to write some third program for packet sorting, which will:
1) Forward DNS requests to netmap pipe 1, so the first app could pick it
2) Forward IGMP requests to netmap pipe 2 so the second app could pick it
3) Forward the remaining packets to host stack, so the host could have Internet access too

Questions:
1) Is it the right architecture?
2) Should I write the "packet sorter" application myself, or there is already a solution for this? As simple as may it be, I wish to make sure that I'm not reinventing the wheel.

**Comment by vmaffione** [comment]
You are welcome to propose a pull request with those modifications to the README.
Actually the README should first of all point to the netmap man page (installed together with netmap).

Performance of the host stack should be slightly worse, because there will be an additional copy between the netmap buffer and the sk_buff. But the only way to figure out the impact is to try and measure. It is even possible to avoid this by properly using hardware receive steering to direct the two types of traffic towards a different set of queues, and then use netmap only on the subset of queues that receive the traffic you want to process with netmap.

You can open a netmap interface many times (in different threads or processes), but accesses to each netmap ring should be exclusive or serialized through same external lock. If you access the same ring concurrently and without serialization, netmap will just allow it but you may get random failures in TXSYNC, RXSYNC or poll(). Alternatively, you could use NR_EXCLUSIVE to enforce exclusive access (see netmap headers).

The multi-processes architecture you propose looks ok, it's a way to handle your use-case re-using modular components.
There is no standard packet demultiplexer, you should write your own. You may use the fe.c example in tutorial to start with, it's kind of related.
Another architecture would be of course to do all the processing in a single program (no modularity). It's up to you to see what works best in terms of CPU consumption and performance, depending on the workload and your machine.

**Comment by SviMik** [comment]
Thank you for the comprehensive answer!

Having some demultiplexer would be a more user-friendly approach, because it gives user the ability to run different applications (even from different authors), add/remove/upgrade/restart them without disturbing the whole interface, and, of course, choose which applications and how many instances of them to run. Imagine a world without wall sockets, when you have to solder wires directly each time you wish to connect a toaster. And don't forget to switch off electricity in the whole building for 2 seconds! :) And of course, "a single program" is definitely not a unix way. Not only because it's hard to maintain, but also if one crashes then all services will fail at once (in worst case you can loose the remote access to your server as well). So having demultiplexer as a separate process would be more fail-safe approach if you have different things on the same interface. I really wished there was some standard one, but if not, then I'll try to write some myself. Maybe even publish it, if it comes out not too ugly :)

**Comment by vmaffione** [comment]
There is also the lb program that is a demultiplexer on netmap pipes. You
could extend that one

Il 5 set 2017 6:56 PM, "SviMik" <notifications@github.com> ha scritto:
