### ISSUE TITLE
nmreplay inject failed with igb

### ISSUE THREAD

**Issue by jllorente** [luigirizzo/netmap#374]
I am attempting to replay a pcap file via nmreplay. I have the same setup working with tcpreplay.
I'm running latest version of netmap.
My system has Intel cards with igb driver, that I have previously patched. The NICs I'm using are "ens2f0" and "ens2f1", which are cross connected with an Ethernet cable.

I was able to successfully run pkt-gen, but for some reason nmreplay fails.

This is using the name of the interface directly, as in pkt-gen, but cannot find the interface:
```
ubuntu@dev:~# nmreplay -v -f edns0.ens2f1.1dst.8M.pcap -i ens2f0                                                                                         
..                                        
664.684 nmreplay_m [  941]      --EEE-- cannot open netmap on ens2f0                                  
..                  
665.393202 main [1275] exiting on abort                                                               
```

Adding the prefix "netmap:" seems to find the interface, but fails to inject:
```                                                                 
ubuntu@dev:~# nmreplay -v -f edns0.ens2f1.1dst.8M.pcap -i netmap:ens2f0              
772.456 main       [ 1246]      running on cores 2 8 4 10                                                 
772.457 readpcap   [  330]      filesize is 1128000024                                                    
772.457 readpcap   [  348]      magic is 0xa1b2c3d4                                                       
772.457 readpcap   [  371]      swap 0 res 1000                                                           
                                                                                                          
772.882 readpcap   [  406]      tot_pkt 8000000 tot_bytes 1000000000 tx_time 11.633873 s first_len 125    
772.882 readpcap   [  421]      first_pkt_time 0.000001 s                                                 
772.882 pcap_prod  [  784]      --- start create 8000000 packets at tail 0                                
772.882 pcap_prod  [  808]      insert     0 len 125 cur_tt 0.000001                                      
774.154 pcap_prod  [  840]      done q->prod_tail:1280000000                                              
774.348 nmreplay_m [  946]      --WWW-- prepare to send packets                                           
774.350433 cons [902] inject failed len 125 now 936112 tx 738454 h 0 t 1280000000 next 40960              
774.457 main       [ 1267]      255 -> 8768940 maxq 0 round 0                                             
774.457 main       [ 1271]      plr nominal 0.000000e+00 actual 0.000000e+00                              
775.000000 cons [902] inject failed len 125 now 936112 tx 738454 h 0 t 1280000000 next 40960              
775.457 main       [ 1267]      0 -> 0 maxq 0 round 0                                                     
775.457 main       [ 1271]      plr nominal 0.000000e+00 actual 0.000000e+00                              
^C775.962 main       [ 1267]    0 -> 0 maxq 0 round 0                                                     
775.962 main       [ 1271]      plr nominal 0.000000e+00 actual 0.000000e+00                              
775.962930 main [1275] exiting on abort                                                                   
776.000000 cons [902] inject failed len 125 now 936112 tx 738454 h 0 t 1280000000 next 40960              
776.000012 cons [911] exiting on abort                                                                    
776.000 nmreplay_m [  949]      --EEE-- exiting on abort                                                  
```

igb driver information:
```
ubuntu@dev:~# modinfo igb                                                         
filename:       /lib/modules/4.8.0-54-generic/updates/drivers/net/ethernet/intel/igb/igb.ko    
version:        5.3.5.12                                                                       
license:        GPL                                                                            
description:    Intel(R) Gigabit Ethernet Linux Driver                                         
author:         Intel Corporation, <e1000-devel@lists.sourceforge.net>                         
srcversion:     DF2F48CF0C887C7838F6512                                                        
```

I have also disabled all offloadings possible from the cards via ethtool, to no avail...
Can someone point me into the right direction?

Thank you!
Jesus

**Comment by vmaffione** [comment]
I don't know how the nmreplay program works, but have you tried to use a
different netmap port, e.g. a vale port ‘vale1:1´?

Il 30 set 2017 8:45 AM, "jllorente" <notifications@github.com> ha scritto:

I am attempting to replay a pcap file via nmreplay. I have the same setup
working with tcpreplay.
I'm running latest version of netmap.
My system has Intel cards with igb driver, that I have previously patched.
The NICs I'm using are "ens2f0" and "ens2f1", which are cross connected
with an Ethernet cable.

I was able to successfully run pkt-gen, but for some reason nmreplay fails.

This is using the name of the interface directly, as in pkt-gen, but cannot
find the interface:

ubuntu@dev:~# nmreplay -v -f edns0.ens2f1.1dst.8M.pcap -i ens2f0
..
664.684 nmreplay_m [  941]      --EEE-- cannot open netmap on ens2f0
..
665.393202 main [1275] exiting on abort

Adding the prefix "netmap:" seems to find the interface, but fails to
inject:

ubuntu@dev:~# nmreplay -v -f edns0.ens2f1.1dst.8M.pcap -i
netmap:ens2f0
772.456 main       [ 1246]      running on cores 2 8 4 10
772.457 readpcap   [  330]      filesize is 1128000024
772.457 readpcap   [  348]      magic is 0xa1b2c3d4
772.457 readpcap   [  371]      swap 0 res 1000

772.882 readpcap   [  406]      tot_pkt 8000000 tot_bytes 1000000000
tx_time 11.633873 s first_len 125
772.882 readpcap   [  421]      first_pkt_time 0.000001 s
772.882 pcap_prod  [  784]      --- start create 8000000 packets at
tail 0
772.882 pcap_prod  [  808]      insert     0 len 125 cur_tt 0.000001
774.154 pcap_prod  [  840]      done q->prod_tail:1280000000
774.348 nmreplay_m [  946]      --WWW-- prepare to send packets
774.350433 cons [902] inject failed len 125 now 936112 tx 738454 h 0 t
1280000000 next 40960
774.457 main       [ 1267]      255 -> 8768940 maxq 0 round 0
774.457 main       [ 1271]      plr nominal 0.000000e+00 actual
0.000000e+00
775.000000 cons [902] inject failed len 125 now 936112 tx 738454 h 0 t
1280000000 next 40960
775.457 main       [ 1267]      0 -> 0 maxq 0 round 0
775.457 main       [ 1271]      plr nominal 0.000000e+00 actual
0.000000e+00
^C775.962 main       [ 1267]    0 -> 0 maxq 0 round 0
775.962 main       [ 1271]      plr nominal 0.000000e+00 actual
0.000000e+00
775.962930 main [1275] exiting on abort
776.000000 cons [902] inject failed len 125 now 936112 tx 738454 h 0 t
1280000000 next 40960
776.000012 cons [911] exiting on abort
776.000 nmreplay_m [  949]      --EEE-- exiting on abort

igb driver information:

ubuntu@dev:~# modinfo igb
filename:
/lib/modules/4.8.0-54-generic/updates/drivers/net/ethernet/intel/igb/igb.ko
version:        5.3.5.12
license:        GPL
description:    Intel(R) Gigabit Ethernet Linux Driver
author:         Intel Corporation, <e1000-devel@lists.sourceforge.net>
srcversion:     DF2F48CF0C887C7838F6512

I have also disabled all offloadings possible from the cards via ethtool,
to no avail...
Can someone point me into the right direction?

Thank you!
Jesus

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/luigirizzo/netmap/issues/374>, or mute the thread

**Comment by jmtilli** [comment]
Hello,

I investigated this with @jllorente. It seems that despite the occasional "inject failed" message, packets are still sent. The bandwidth monitoring applications however do not show any send bandwidth because netmap bypasses those code paths! So if the promiscuous mode on the receiving NIC is off and the MAC address is incorrect, there may be no mechanism to verify that packets are actually being sent at full blast.

@jllorente can confirm whether this bug can be closed, but my understanding is that we now had everything working, apart from a strange flow control issue that appeared when flow control autonegotiation, RX flow control and TX flow control on both NICs were turned off... But this is probably a different issue.

Of course, it is a good question whether nmreplay should be more user friendly, specifically by printing a million packets per second and gigabits per second figure every second or every two seconds or so. This would allow the user to verify that packets are actually being sent.

**Comment by giuseppelettieri** [comment]
The current version of nmreplay should print ```inject failed``` only when, well, inject fails.

**Comment by jmtilli** [comment]
But is it possible that inject fails in normal operation? I've seen it happen and had to write the following helper function in my applications to make them work:

    static inline void nm_my_inject(struct nm_desc *nmd, void *data, size_t sz)
    {
      int i, j;
      for (i = 0; i < 3; i++)
      {
        for (j = 0; j < 3; j++)
        {
          if (nm_inject(nmd, data, sz) == 0)
          {
            struct pollfd pollfd;
            pollfd.fd = nmd->fd;
            pollfd.events = POLLOUT;
            poll(&pollfd, 1, 0);
          }
          else
          {
            return;
          }
        }
        ioctl(nmd->fd, NIOCTXSYNC, NULL);
      }
    }

**Comment by giuseppelettieri** [comment]
Yes, it fails if there is no room in any of the rings. Your helper function is fine, assuming you want to block until some room becomes available.

**Comment by giuseppelettieri** [comment]
Some more info: please consider that ```nm_inject``` only puts the packet in a netmap ring, but it does not actually flushes it to the card. For that you need to either ```poll``` or ```ioctl(fd, NICTXSYNC)```. If you never do that, packets will simply stack there until the rings fill up.
