### ISSUE TITLE
Linux Kernel panics when using Netmap in Linux containers environment

### ISSUE THREAD

**Issue by firthmj** [luigirizzo/netmap#382]
Experimenting with Netmap and Linux containers, I am seeing a lot of kernel panics.

This is with the head of "master" (commit 1597e0cb9e7b541f11d9c9aad2afe620ea339596), on a up-to-date Debian 9 system (kernel package is "linux-image-4.9.0-4-amd64 4.9.51-1")

Most crashes have been seen with some traffic crossing an Intel 10G NIC (a new one, with the i40e driver), but one crash was just transferring traffic internally between containers.

The environment is:

- Debian 9 host, with at least two "bind mount" LXC containers (The "lxc.conf" files available if needed).
- Two "veth" connections into each container, one for management bridged in the host using Linux "bridge-utils", and one for the "data path".
- (Optionally create a second Linux bridge between the "data path" connections to prove communications without Netmap active)
- Create a "vale" switch in the host to connect the "data path" veth instances together (and / or to the Intel NIC):
vale-ctl -a vale1:ve_hosta1
vale-ctl -a vale1:ve_hostb1
- It seems that the "veth" support for Netmap then also automatically puts the "container" end of the "veth" links into Netmap mode, as communications between the two containers.
- Run "bridge" in each container to bridge the "veth" back to the container host stack:
bridge -i netmap:eth1
- It should now be possible to "ping" between the two containers.

When trying to check or shut this setup down, a Kernel panic is likely. Sometimes it was seen when running "vale-ctl" to check the VALE switch ports in the host. Sometimes when pressing "Ctrl-C" to exit out of one of the "bridge" instances.

Because it is a "hard kernel crash" it is hard to extract logs, but I do have a picture of a screen with the kernel panic output.

**Comment by vmaffione** [comment]
A kernel panic output can be useful.

You should simplify the setup as much as possible to figure out where the issue is. For instance, there is no need to add the intel NIC to VALE, since you are pinging between containers.
You could also get rid of the bridge program in the containers, and ping (unidirectionally) through pkt-gen:

Container 1:
````
# pkt-gen -i eth1 -f rx
````

Container 2:
````
# pkt-gen -i eth1 -f tx -R 1
````

You see the crash on unregif or vale-ctl, so it should be something not related to the datapath.
In any case, to collect crashes you can run the whole thing inside a VM (e.g. QEMU), redirect the console to the emulated serial port and configure the hypervisor to attach the emulated serial port to a file or TCP connection. I can share the setup if you wish.

**Comment by giuseppelettieri** [comment]
Hi @firthmj. The latest master (commit https://github.com/luigirizzo/netmap/commit/2d07ae648a09fe23566581e61b9006265113f02f) contains a fix for a bug that may be related to the panics you are seeing. May you give it a try?

**Comment by firthmj** [comment]
Hi,

I’m on holiday this week, but will try the latest version on Monday 30th and see if the updates fix the issue. If not, I will try and build a VM environment as Vincenzo suggested and try and capture details of what is happening.

**Comment by firthmj** [comment]
Apologies for the very delayed response, but I have been diverted on to a lot of other tasks!

The changes made by Giuseppe on October 22nd appear to have fixed my issues - I have seen no more Netmap related kernel panics since upating.
