### ISSUE TITLE
Using VALE to talk to the host/Linux network stack

### ISSUE THREAD

**Issue by sqwishy** [luigirizzo/netmap#394]
What I'm trying to do is have a separate virtual interface on the system that Linux can route traffic into that would go into a netmap program, similar to a TUN device. I understand this is possible using the host ring on a normal interface, but it seems a virtual interface would be more appropriate for my use case.

I'm wondering if I can use VALE switches this way, and move packets between the Linux network stack and a netmap program. Is that possible/a good/bad idea or is there something else in netmap that might work better for this?

From what I can tell a veth pair would not work since both ends need to be using the veth in netmap mode for communication to work.

**Comment by vmaffione** [comment]
You can do that with a tap interface. You could also do that with a vale port, but you need a persistent one, to be created with vale-ctl -n

**Comment by sqwishy** [comment]
I couldn't seem to use `vale-ctl` to create an interface that would let Linux and netmap talk to each other. I tried attaching it to a switch and also using `-h` to do the host thing. I tried to use pkt-gen to read traffic from the host that I sent from Linux into the device. Also dmesg said something about `netmap_interp_ringid      host rings not supported`. So I'm a little confused about how to use this. I might be going at this all wrong.

I'd rather not use a TUN device on its own since it's quite slow. Unless there is a way to use with netmap but I didn't see anything about that.

**Comment by vmaffione** [comment]
I think we misunderstood each other. I just wanted to say that if you want to intercept the packets that host kernel transmits to an interface, you can use the host rings of a TAP interface. So you would use a TAP (virtual) interface rather than a phyisical NIC; but still you need to use the host rings.

Maybe you don't want to use the host rings at all. In that case you could use a pair of veths and force the emulated netmap mode (either setting admode=2 or by not patching the veth module, e.g. with `--no-drivers=veth.c`). In this situation you can use only one end in netmap mode.

**Comment by sqwishy** [comment]
I looked into the veth stuff a bit and using unpatched drivers seems too slow for my use case.

If it's fast enough, I can try using a TUN/TAP interface with netmap; that didn't seem to work but I might have been doing something wrong.

So VALE wouldn't really help me here I'm guessing? What I'm picturing is making an interface/port with vale (called `vl0` for example) and opening `vl0^` in netmap mode to send/receive with Linux on that interface. But it sounds like that's just not what it's for.

**Comment by vmaffione** [comment]
The netmap way to let the network stack and an user-space application to exchange packets is using the host rings of a network interface registered into the kernel. This mechanism is not particularly efficient, because it cannot be and because it is not part of the netmap use cases. But the mechanism does exist for compatibility and to let a small portion of the traffic to be handled by the host stack instead of the netmap application (e.g. ssh traffic or other control-plane traffic like BGP or OSPF).
If host rings (or veth in emulated mode) are not fast enough for you, then you won't find a better solution with netmap. It also depends on your definition of "slow": how many pps? which latency?

TAP is not faster than veth/host rings. Anyway, I don't see how you can use TAP and netmap without using its host rings, because both netmap and kernel stack use the "net side" of the TAP, and the "file descriptor side" can't be used with netmap, obviously.

VALE ports can't be currently used by the linux network stack (to transmit and receive), as they can only be opened in netmap mode. We could extend that, but it would be less efficient than using the host rings of any interface.

**Comment by sqwishy** [comment]
That's useful information, thanks.

>It also depends on your definition of "slow": how many pps? which latency?

I'm aiming for something as fast as VALE but maybe that's unrealistic due to overhead of going through the Linux networking stack. Something at least faster than a TUN device. Last I checked, I was only able to write() 250k pps to a TUN device. Or something like that. I didn't test very rigorously.

It looks like `pkt-gen` can send to the host ring for a TUN device and Linux will see it. I didn't notice this before, I think I was using the `ping` function and it was telling me it couldn't send. And that seems to be quite a bit faster, between 900Kpps and 1.4Mpps.

It makes sense that performance between netmap and the host and netmap and the device is going to be different; since they're completely different pathways. I guess I would have assumed that it'd be faster to the host since it's so much closer but it's probably also more complex.

I'm okay if you want to close this. Thanks for your help here and on the other question I had.

**Comment by vmaffione** [comment]
It's unrealistic indeed. If linux fast were half as fast as VALE then netmap/DPDK wouldn't be needed.
Yes, numbers around 1Mpps make sense.
