### ISSUE TITLE
netmap_transmit error

### ISSUE THREAD

**Issue by sinainnet** [luigirizzo/netmap#426]
Hi,

During packet capturing and transmitting, I've get the following error in syslog.

`netmap_tanrsmit eth0 full hwcur 0 hwtail 0 qlen 4095 len 42 m ffff885e79fae800`

As I searched the source code, this log appears if the following condition gets true.
(it is in files sys/dev/netmap/nemap.c:netmap_transmit())
`if (busy + mbq_len(q) >= kring->nkr_num_slots - 1)`

I want to ask why this happens.
And, If it depends of the netmap or ixgbe modules parameters, what are the parameters used in calculation of nkr_num_slots?

**Comment by vmaffione** [comment]
Hi,
  It simply means that your kernel is trying to transmit packets to a network interface that you turned into netmap mode (e.g. because of socket applications sending packets, or kernel-generated ICMP traffic).
In this case netmap intercepts those packets and puts them in an internal queue, so that your netmap application can read them from the "host RX ring". However, it seems your application is not reading from the host RX ring (`hwcur==0`), so the internal queue gets full and starts to drop.

`nkr_num_slots` is simply the number of slots used by the NIC for each ring (the same one that you can see from `ethtool -g ethX`

**Comment by sinainnet** [comment]
Does this drop cause drop in the card RX ring?

**Comment by vmaffione** [comment]
No, it's completely unrelated. If you want to learn what host rings are (and in particular what host RX ring is), you can look at the intro.pdf in the netmap tutorial https://github.com/vmaffione/netmap-tutorial

**Comment by sinainnet** [comment]
Thanks a lot. It was very helpful.
