### ISSUE TITLE
oversized packets received when using i40e driver

### ISSUE THREAD

**Issue by matiaselo** [luigirizzo/netmap#429]
Hi,

Couple issues/questions. With the latest code (3415ba93 on Ubuntu 16.04 - 4.4.0-109-generic) and i40e drivers oversized packets (length > MTU) are not dropped by the netmap interface. I assume the interface should obey MTU? When using ixgbe drivers oversized packets are dropped.

Additionally, if received packet length is larger than nr_buf_size, received packet ends up being fragmented (NS_MOREFRAG is set).

In netmap.h:
```
#define	NS_MOREFRAG	0x0020	/* packet has more fragments */
 	/*
	 * (VALE ports only)
	 * Set on all but the last slot of a multi-segment packet.
	 * The 'len' field refers to the individual fragment.
	 */
```
This is a bit confusing since both ixgbe and i40e drivers use this flag. Also, pkt-gen (rx mode) doesn't handle fragmented packets properly and ends up printing invalid packet rate.

**Comment by vmaffione** [comment]
Hi,
  Yes, actually it's not true anymore that `NS_MOREFRAG` is used by VALE ports only. I just updated the comment you pointed out to reflect this (thanks for spotting it).

Regarding the MTU, I think it depends on the NIC hardware, and not on netmap. Netmap does not drop RX packet, and actually it can't do that, by design. You can look at `ixgbe_netmap_rxsync` and `i40e_netmap_rxsync` to see that there is no code that drops. So the difference in behaviour is due to the NIC hardware or maybe driver configuration.

Regarding pkt-gen: true, `receiver_body` does not currently support `NS_MOREFRAG`, while `sender_body` does. We should support that (any patch welcome).

**Comment by matiaselo** [comment]
Thanks for the prompt answer!
