### ISSUE TITLE
Question regarding default status of NICs

### ISSUE THREAD

**Issue by fklassen** [luigirizzo/netmap#436]
I'm just starting work on [this issue in Tcpreplay with netmap](https://github.com/appneta/tcpreplay/issues/424) and am having problems just setting up my Linux test bed.

First of all, my Linux machine that I haven't touched for years can run old copies of Tcpreplay. But when I use a copy of Tcpreplay compiled against the latest version of `netmap`, it fails. This is not a surprise. I find that the `netmap` API changes continually. I have to test the version of `netmap` in my application, and adjust accordingly. For example, I call a version 3 netmap differently than a version 4.

My issue is that I am having trouble setting up a new test machine. In the past, I would swap out my original `igb` or `ixgbe` driver with my `netmap` version, install the `netmap.ko` module,  then reboot. My machine would up in `normal` mode, allowing me to get a DHCP address and connect in. But that isn't working for me anymore. I think the interface is in Read-Only or netmap mode.

My question is, has something changed with the default config? Do the drivers come up in netmap mode by default? Or is there something I can do to allow me to have the drivers come up normally so I can use the regular TCP stack until I am ready to run `tcpreplay --netmap ...`.

**Comment by giuseppelettieri** [comment]
Nothing has changed in the configuration, the interfaces are not automatically put into netmap mode. The only thing that I can think of, is that we are now patching the drivers that are distributed by Intel, instead of the drivers that come with your kernel. If you have the full kernel sources (like it used to be necessary), you can try to switch back to the old method:

```
cd netmap
make distclean
./configure --no-ext-drivers
make
```

You may have to pass the location of your kernel surces to ./configure. Use the --kernel-sources=... option for that.

**Comment by fklassen** [comment]
Hey, that worked. I was able to get that working. 

Also, it seems that nothing has changed in the API that requires any changes on my end. Nice to see the downward compatibility. The issue reported above was not a netmap issue.
