### ISSUE TITLE
TX stuck on completely full pipe

### ISSUE THREAD

**Issue by larseggert** [luigirizzo/netmap#457]
I *think* I see an issue (don't have proper instrumentation in place at the moment) when I fill all slots on a pipe and then signal TX that nothing seems to happen, i.e, head/tail/cur don't change. On less-than-completely-full pipes things work.

**Comment by jolisexy** [comment]
hello how are you me it is natacha I am unmarried Canadian here to make me friends here is my skype natacha dipou sorry for the inconvenience thank you and have a good day as you

**Comment by pothos** [comment]
@larseggert Did you find out more? I also have full pipes that don't transmit anymore and will try to look into it.

**Comment by vonami** [comment]
I guess I have experienced a similar issue. Disabling flow control helped in my case.

**Comment by pothos** [comment]
@vonami I thought this here is about netmap pipes, so no device is involved. My setting: dispatch process writes too many packets on "dev}1" and then can't write because the pipe is full (uses implicit TX on ppoll POLLIN). The receiver process only receives a short burst in the beginning.

**Comment by pothos** [comment]
For the problem appearing with implicit TX (TX_POLL is default) it helps to force a `NIOCTXSYNC ioctl` but it slows things down a lot.

**Comment by pothos** [comment]
Here is sender code to reproduce it: https://gist.github.com/pothos/998131170b0107f31ad3ce5aba34dd2f

Strangely it works if the TX_POLL sender is used after a TXSYNC sender (leaving pkt-gen -f rx running). Working in this example code means only 500 pkt/s because of the poll timeout, but just to demonstrate wheather the pipe is stuck or not.

**Comment by giuseppelettieri** [comment]
I can't reproduce this bug. @pothos, your example code contains an error at line 11: you are waiting for a ```POLLIN``` event instead of the correct ```POLLOUT```.

**Comment by giuseppelettieri** [comment]
OK, it is a bit subtle, but I think that the current behavior is correct. ```TX_POLL``` will send packets automatically, but it has no obligation to inform you that there is new space available in the tx ring. For that, you need an explicit ```POLLOUT```.

**Comment by pothos** [comment]
Yes, I'm not using the poll to wait for new TX space, but just as a TXSYNC alternative in this reduced example. With using 0 as timeout it is like busy polling and I expect it to eventually move the packets - but only the first transaction takes place and afterwards the pipe stays full.

**Comment by giuseppelettieri** [comment]
If you don't ask for ```POLLOUT```, available space may not be reported to you, even when it is there. This is why your sender stalls.

**Comment by pothos** [comment]
@giuseppelettieri Thanks for the response. Ok, to really understand it now, `head`/`cur`/`tail` is not guaranteed to be updated even if packets were sent but it *may* be? Strange that I only run into this issue with pipes. Since  `POLLOUT` is not an option, I use an additional `TXSYNC` to work around this.
