### ISSUE TITLE
how to use batching to increase netmap performance

### ISSUE THREAD

**Issue by murali-rd** [luigirizzo/netmap#469]
hi,
based on bench marking test for high speed packet processing by gallen mueller the netmap performance can be increased by increasing the batch size as it will decrease the system call further (suggested batch size is 256) . but when i run the netmap in my setup (10g ixgbe link) the batch size achieved is around 13 ~ 16. the netmap_poll implementation doesn't seem to do any batching related stuff based on my understanding. so i assume the only way to increase batching is by increasing the burst size in pkt-gen application (any netmap application). is there any way to increase the batch size so that system call cost is further reduced.

regards,
murali

**Comment by vmaffione** [comment]
Yes, one of the main point of netmap is indeed to work with a batch as large as possible.
pkt-gen already tries to use a batch of 512 packets by default (`-b` option will change the default).
The actual batch size (the one reported by `avg_batch`), however, depends on the dynamic behaviour of the sender application and the netmap port. If the netmap port is faster to drain packets than the application is able to send, then you will see large batches (up to 512). Otherwise (like in your case), the batch can be as low as 1. This may happen because of misconfiguration (e.g. maybe you have ethernet flow control enabled or you need a more aggressive interrupt moderation), or because of the relative speed of application and netmap port are really like that.
One way to increment the batch size is to add a `usleep()` with a proper number of microseconds after the `poll` call in `sender_body`. Also see #460

**Comment by murali-rd** [comment]
hi vmaffione,

Thank you for replay. i was wondering why cant netmap_poll or netmap_ioctl be changed basically wait for certain number of packets and then sync. i tried modifying the netmap_poll from 
found = ((kring->rcur) != (kring->rtail));
to 
found = ((kring->rcur + 100) != (kring->rtail));  /*just wait for 100 packets*/
but the cpu cycles increased almost 5 times. any rational for this. basically cant we do SO_RCVLOWAT kind of implementation inside netmap poll/ioctl?

thanks and regards
murali

**Comment by murali-rd** [comment]
hi vmaffione,

The further changes you mentioned increased the batch size to 400 (improves performance too) but the issue is it is impacting the throughput. the throughput drops to 10Mbps from actual 512Mbps before this changes. is this due to increased latency and also delay in sys_poll wakeup.

thanks & regards,
murali

**Comment by vmaffione** [comment]
For sure throughput cannot be sacrificed in that way.
I don't know which changes you made, but I was trying to come up with a patch (see attached).
Unfortunately, this is still not complete, because `netmap_notify` unconditionally wakes up the poll()er threads, therefore incuring in all the associated wakeup overhead and poll cost. To wake up conditionally (e.g. when `tail` overcomes `cur`), we should lock the kring, but this would change the locking patterns substantially, so it may adverse performance significantly (even if `cur==head`) ...
[netmap-cur.txt](https://github.com/luigirizzo/netmap/files/1897705/netmap-cur.txt)

**Comment by murali-rd** [comment]
hi vmaffione,

i did change similar to nm_kring_should_wakeup and commented synch function checks as it was just for initial testing. but from your explanation i didn't understand how poll gets woken up unconditionally, as netmap_notify  is only invoked in case of freebsd i think and also when found != 0 and found will be 1 only if we have received desired number of packets.

#ifndef linux
				kring->nm_notify(kring, 0);
#endif /* linux */

can you please help me understand this.

thanks and regards,
murali

**Comment by vmaffione** [comment]
Yes, that call to `nm_notify` is not the primary one.
`nm_notify` is called from the driver interrupt routine (or the NAPI routine in case of linux).
Interrupt routines call `netmap_rx_irq` or `netmap_tx_irq`, which in turn call `nm_notify`.
See also patches in `LINUX/final-patches`

**Comment by murali-rd** [comment]
netmap_notify is waking up poll for every packet received (or based on NAPI policy), so this was happening before too. now if we modify the netmap_poll to accumulate more interrupt/packets it should not affect the performance right. so does we really need to modify netmap_notify?
also rcur and rhead are modified in netmap_poll once netmap_notify wakes it up, so making netmap_notify conditional will it will help?

thanks and regards,
murali

**Comment by giuseppelettieri** [comment]
The ability to move cur beyond tail has been in wish-list for a long time, since it is also useful in the tx path (the sender may need more than one slot, e.g., to send a multi-slot jumbo frame). I would like to see it done, and we can think of optimizing netmap_notify() later.

**Comment by vmaffione** [comment]
The patch above already modifies `netmap_poll` to accumulate more packets before returing POLLIN or POLLOUT to the application. But still at each call to `netmap_notify` the application needs to wake up and call `netmap_poll` again, and the latter will find out that more slots are needed and tell the kernel to go to sleep again (this is expensive, so the performance is affected).

**Comment by murali-rd** [comment]
hi vmaffione ,

For the patch we should also update utility api's like  nm_ring_empty, nm_ring_space etc (should be based on head rather than cur) and pkt-gen app.

regards,
murali

**Comment by murali-rd** [comment]
for the netmap_notify i did made changes like below : 
/* default notify callback */
static int
netmap_notify(struct netmap_kring *kring, int flags)
{
	struct netmap_adapter *na = kring->na;
	enum txrx t = kring->tx;
	uint32_t revents = 0, found = 0;

	if (unlikely(nm_kr_tryget(kring, 1, &revents)))
	{
		return NM_IRQ_RESCHED;
	}
	else
	{
	       found =  nm_kring_should_wakeup(kring);
	       nm_kr_put(kring);
       }

       if(found)
      {
        	nm_os_selwakeup(&kring->si);
        	/* optimization: avoid a wake up on the global
        	 * queue if nobody has registered for more
        	 * than one ring
        	 */
        	if (na->si_users[t] > 0)
        		nm_os_selwakeup(&na->si[t]);
      }
	return NM_IRQ_COMPLETED;
	
}

but the effect on performance is not that much visible. can you please check if these changes are ok.

thanks and regards,
murali

**Comment by vmaffione** [comment]
Yes, ` nm_ring_empty` and ` nm_ring_space` also need to be updated as you say. However, no changes are necessary to pkt-gen, and not even recompilation, because pkt-gen always sets `head=cur`, which is compatible with the API change.
One can modify `pkt--gen` to benefit from the new feature, but this can happen afterwards.

Your proposed patch `nm_notify` has no effect, because no one is updating `kring->rtail and `kring->rhead`. This is done by the `nm_sync` callback and the prologues (see `netmap_poll`).
So you should do that before calling `nm_kring_should_wakeup`. Our idea would be to try to do these operations (that are potentially expensive and change the locking scheme) only when `rcur` is beyond `rtail`. With this approach, `netmap_poll` would need to set a flag in the `kring` to tell `nm_notify` to perform the prologue/sync/should-wake-up sequence.

**Comment by murali-rd** [comment]
"Our idea would be to try to do these operations (that are potentially expensive and change the locking scheme) only when rcur is beyond rtail. With this approach,netmap_poll would need to set a flag in the kring to tell nm_notify to perform the prologue/sync/should-wake-up sequence."
==>
can you please elaborate on change in locking scheme, does it mean same as what i used in nm_notify patch i sent before. (nm_kr_tryget and nm_kr_put)

thanks and regards,
murali

**Comment by vmaffione** [comment]
Yes, we need to lock the `kring` in the same way you did.
When I say "the locking scheme changes" I mean that so far the `kring` lock is de facto always uncontended: it's true that even now two threads could try to access the same kring concurrently, but this is discouraged and it is an error unless the application implements its own locking scheme.
The `kring` lock is there to protect from malicious applications and to implement an up/down protocol.

If now we allow the `nm_notify` to lock the `kring`, that lock becomes contended between the netmap application and the interrupt thread. This contention is expected to have a negative effect on performance, that's why we don't want `nm_notify` to unconditionally try to take the lock.

**Comment by murali-rd** [comment]
hi vmaffione ,

But the kring and locks are not available in user space, so how to lock or is there any different way to access and lock them in user space.

thanks and regards,
murali

**Comment by murali-rd** [comment]
ok. but if nm_kr_tryget is invoked both in netmap_poll and netmap_notify before sync then this conflict should not be there right.

thanks and regards,
murali

**Comment by vmaffione** [comment]
Nothing prevents `poll` or `ioctl` to be called at the same time `netmap_rx_irq` or `netmap_tx_irq` is called, so the two threads can contend for the lock.
Moreover, two threads accessing the lock from different cores always generate a conflict, even if they don't try to access it at the same time, because of cache misses on the lock internal shared variable. The cache line of the lock will ping-pong between the two threads in any case.

**Comment by murali-rd** [comment]
hi,
contention for lock will slow down the performance which for time being ok for my test, but after I did following changes system reboots. do you see any issue with following change.

static int
netmap_notify(struct netmap_kring *kring, int flags)
{
	struct netmap_adapter *na = kring->na;
	enum txrx t = kring->tx;
	uint32_t revents = 0, found = 0;

	if (unlikely(nm_kr_tryget(kring, 1, &revents)))
	{
		return NM_IRQ_RESCHED;
	}
	else
	{
		if (nm_rxsync_prologue(kring, kring->ring) >= kring->nkr_num_slots) {
			netmap_ring_reinit(kring);
			revents |= POLLERR;
		}
		/* now we can use kring->rcur, rtail */

		/* Clear the NR_FORWARD flag anyway, it may be set by
		 * the nm_sync() below only on for the host RX ring (see
		 * netmap_rxsync_from_host()). */
		kring->nr_kflags &= ~NR_FORWARD;
		if (kring->nm_sync(kring, NAF_CAN_FORWARD_DOWN))
			revents |= POLLERR;
		else
			nm_sync_finalize(kring);
		ring_timestamp_set(kring->ring);			
            found =  nm_kring_should_wakeup(kring);
            nm_kr_put(kring);
       }

       if(found)
      {
        	nm_os_selwakeup(&kring->si);
        	/* optimization: avoid a wake up on the global
        	 * queue if nobody has registered for more
        	 * than one ring
        	 */
        	if (na->si_users[t] > 0)
        		nm_os_selwakeup(&na->si[t]);
      }
	return NM_IRQ_COMPLETED;
	
}

thanks and regards,
murali

**Comment by vmaffione** [comment]
I guess you mean you get a crash.
I think you should always return `NM_IRQ_COMPLETED`.
And you need to call the right prologue, not always the rxsync one.
