### ISSUE TITLE
netmap_transmit           lo drop mbuf that needs offloadings

### ISSUE THREAD

**Issue by kogdenko** [luigirizzo/netmap#479]
Hello!

I am trying to use netmap lo interface in linux:
```bash
./bridge -i 'netmap:lo'
```

Then I send tcp packets:
```bash
nc 127.0.0.1 80
```

And get no packets in bridge, but errors in dmesg:
```dmesg
[218789.412913] 707.069363 [3148] netmap_transmit           lo drop mbuf that needs offloadings
[218790.432094] 708.088540 [3148] netmap_transmit           lo drop mbuf that needs offloadings
[218792.480093] 710.136539 [3148] netmap_transmit           lo drop mbuf that needs offloadings
```

I know that I must disable offloadings,
but there is no way to disable offloadings on lo:
```bash
[root@fx8350 ~]# ethtool -K lo rx off tx off
Cannot change rx-checksumming
Cannot change tx-checksumming
Could not change any device features
```

What am I dong wrong?
Is there any way to receive tcp packet (sent from host SOCK_STREAM app (not SOCK_RAW))
in netmap app on lo interface in linux?

Thank you!

**Comment by vmaffione** [comment]
Hi,
  If offloadings cannot be changed on `lo` you simply cannot use `lo`.

If your goal is to let a netmap application intercept TCP traffic produced by a local application, you can just use any other network interface (physical or virtual), so that you can disable the offloadings.
In the netmap application you will then intercept the packets by reading from the host RX ring.
Assuming 'eth0' is the interface where netcat traffic is routed:
`````
$ nc 10.0.0.1 80
`````
and you should see the SYN packet with packet gen
`````
$ sudo pkt-gen -i netmap:eth0^ -X
`````
Or you can let the traffic pass to eth0
````
$ sudo bridge netmap:eth0
````

**Comment by kogdenko** [comment]
Thank you for your reply!

My goal is to let netmap apllication intercept TCP traffic produced by local application _and_ going
to localhost. I can't use any other interface except lo, because all local traffic going from localhost to localhost will be routed to lo.
I need somehow disable offloadings.

**Comment by vmaffione** [comment]
You could try to workaround the issue by using `veth` interfaces and running your local application inside a container.
Or you can try to patch netmap to disable this check, at your own risk.
````
diff --git a/sys/dev/netmap/netmap.c b/sys/dev/netmap/netmap.c
index a753f548..fb2d5b0c 100644
--- a/sys/dev/netmap/netmap.c
+++ b/sys/dev/netmap/netmap.c
@@ -3637,11 +3637,6 @@ netmap_transmit(struct ifnet *ifp, struct mbuf *m)
                goto done;
        }
 
-       if (nm_os_mbuf_has_offld(m)) {
-               RD(1, "%s drop mbuf that needs offloadings", na->name);
-               goto done;
-       }
-
        /* protect against netmap_rxsync_from_host(), netmap_sw_to_nic()
         * and maybe other instances of netmap_transmit (the latter
         * not possible on Linux).
````

**Comment by vmaffione** [comment]
Thinking more about that, it should not be dangerous at all, because we still check for the skb length to fit a netmap buffer.
It's just a matter of consistency: since netmap does not handle unchecksummed or TSO packet,
we prevent them to be posted to the host RX ring, because otherwise an application could forward them somewhere with the wrong checksum.

So we could avoid dropping and just log the warning.
