### ISSUE TITLE
connect netmap vale interface with linux bridge...

### ISSUE THREAD

**Issue by msundius** [luigirizzo/netmap#482]
I am working on a project to support layer 2 tunnelling for many different clients. each provisioning policy (tunnel) has its own virtual interface which is connected to a linux bridge which in turn is connected to the Ethernet. My goal is to replace the tap with your netmap, to that end I have installed netmap and converted my code to use netmap api, I have used vale-ctl to create a virtual interface vi0 which I connect to a vale bridge
 
  vale-ctl -a vale0:vi01

and connect vale0 to my linux bridge br01

   vale-ctl -a vale0:br01

so now I have

 (my application)-(netmap)-vi01-vale0-br01-eth1

on the internet side we send data from a udp port. so the whole system looks like this:
pc1  ---- eth1-br01-vale0-vi01-(netmap)-(my app)-(udp port x)-eth2    -- internet

internet  -- eth2-(udp-port-x)-(my application)-(netmap)-vi01-vale0-br01-en01 --- pc2

When I try to contact PC2 from PC1, the arp broadcast request gets through, but the reply does not. I'm suspecting it is dropped between the br01 and my app on the return trip on the far side of the tunnel (close to pc2).  I can see the arp reply at Br01, but it never shows up in my application.

I'm wondering is this a reasonable way to configure vale?

is there a way to ensure that vale0 (that's the vale bridge rite?) passes everything and ensure it does not try to do any smart bridging? when connecting to a bridge with vale-ctl, how does my linux bridge know who is on that port, as there could be many ports connected to vale0....

note that the reason I keep the br01, is that there is a great deal of other software that relies on it. (layer 3 tunnels and some other local provisioning), so it is difficult to get rid of.

**Comment by vmaffione** [comment]
VALE by default is just a standard L2 learning bridge. I don't think your issue is due to VALE itself, but rather I think that attaching br0 to vale0 is probably not a good idea.
If you want to connect br0 to vale0, you should use a patch port (a veth pair)
````
# brctl addif br0 veth0
# vale-ctl -a vale0:veth1
````
but make sure that you are using the unpatched veth driver (emulated netmap), or it won't work (see LINUX/README).

In any case, it's not probably a good idea to let both br0 and vale0 be in the datapath, because br0 is way slower than vale0. It's likely that vale0 will not help improving performance as long as br0 is on the way.
As already discussed in many other issues, a prerequisite to really benefit from netmap is to use netmap all along the datapath, up to the NIC hardware. Interactions with the Linux network stack are possible (e.g. using the host rings) but they should only be used for a small part of the traffic (e.g. control traffic).
IOW netmap does not magically improve your application performance, but you need to deploy it in a way that it allows you to minimize the overall per-packet overhead.

**Comment by msundius** [comment]
Hi Vincenzo,

Thanks for the email. After I sent the question, I realized that I could
create another virtual ethernet and attach it to a the stack with vale-ctl
-h... so VALE acts as the learning bridge and is connected to the nic
directly and my virtual port as well as the one for the local
administration apps. I was thinking that attaching a ip right to the bridge
was weird.

Anyhow I'm glad that you confirmed that I'm on the right path!!! it seems
to be passing traffic now.

thanks again.
Mike
