### ISSUE TITLE
Host TX ring 0 stays empty, 4 works

### ISSUE THREAD

**Issue by pothos** [luigirizzo/netmap#499]
Hello,

maybe this problem arises from my usage, but when I attach one program to  `netmap:enp1s0f0^` the host rings are empty for `ping`. Also if first one program is attached to `netmap:enp1s0f0` and then the next to `netmap:enp1s0f0^` the host rings are empty. With only one program `netmap:enp1s0f0*` however it works to get the packets from `ping` on the host.

Thanks for an answer

**Comment by giuseppelettieri** [comment]
The first and last cases work as expected: ```netmap:enp1s0f0^``` should receive all the traffic sent by the local host stack and directed to the rings of ```enp1s0f0``` *that are in netmap mode*. If you open only ```netmap:enp1s0f0^``` you are not putting any real ring in netmap mode, and therefore you see no packets.  Conversely, by opening ```netmap:enp1s0f0*```, you put all of them in netmap mode and therefore you see all the traffic in the host rings.

The second case, instead, is not working as expected, since ```netmap:enp1s0f0``` plus ```netmap:enp1s0f0^``` should be equivalent to ```netmap:enp1s0f0*```. However, I cannot reproduce your error. Can you give additional details on what you are doing in the second case?

**Comment by pothos** [comment]
I don't know why I did come to this conclusion last time when testing with `pkg-gen -f rx` but now it works. So the problem is in my own code which seems to do something different to `pkg-gen`.

**Comment by pothos** [comment]
Now I found my problem, it was not in the receive code but my code cannot send. This can be reproduced with `pkg-gen` in the following way. `pkt-gen -f tx -i eth^` works, because it uses `NETMAP_TXRING(nifp, i)` with `i = first_tx_ring`. But `pkt-gen -f ping -i eth^` does not work because it uses `NETMAP_TXRING(nifp, 0)`. If I change 0 to 4 in this line which is the value of `first_tx_ring`, then pings are sent.

**Comment by giuseppelettieri** [comment]
Right. Do you want to create a merge request with a fix for pkt-gen? I see that ```pong_body``` has the same problem.
