### ISSUE TITLE
Can't create pipe within VM when Netmap-Passthrough is used

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#517]
I tested if a Netmap pipe can be created within a VM in combination with `ptnetmap-guest-driver`.

It works with a `virtio-net` interface:
```
bridge -i netmap:eth0 -i netmap:eth0{1
...
```

But it crashes with a `ptnet` interface:
```
bridge -i netmap:eth1 -i netmap:eth1{1

470.844335 nm_open [820] netmap_user.h (commit 0608526df98309e165790ac127f6f05fee2e9c01)
[13377.612402] 470.846143 [2041] nm_os_pt_memdev_iomap     === BAR 1 start f8000000 len 4000000 mem_size 2868000 ===
[13377.615207] ptnet_nm_config: txr 1, rxr 1, txd 1024, rxd 1024, rxbufsz 2048
qemu-system-x86_64: Unable to set vnet-hdr length 12 on netmap:pipe1{1: No such device or address
470.871407 nm_open [820] netmap_user.h (commit 0608526df98309e165790ac127f6f05fee2e9c01)
[13377.639152] 470.872896 [2648] netmap_mem_pt_guest_rings_create Error: interface           (null) is not in passthrough
470.875834 nm_open [947] NIOCREGIF failed: No error information netmap:eth1{1
470.877313 main [263] cannot open netmap:eth1{1
[13377.644775] ptnet_nm_register: Exit netmap mode, re-enable interrupts
```

I'm not sure if this should work or if its a valid limitation of Netmap-Passthrough mode.

**Comment by giuseppelettieri** [comment]
No, you can't create pipes, or anything else for that matter, in the same memory area as the passed-through interface. It is a limitation of the current implementation.

**Comment by ramaza** [comment]
I see.

For an experimental setup would you say it's legit to workaround a missing pipe by adding two additional ptnet-interfaces to a Qemu process and connect this two additional interfaces back to back.

I tested the following scenario and it seems to work. Although I'm not sure what performance penalty to expect.

```
...
-netdev netmap,ifname=netmap:pipe0{1,passthrough=on,id=eth0 \
...
-netdev netmap,ifname=netmap:pipe1{1,passthrough=on,id=eth1 \
...
-netdev netmap,ifname=netmap:pipe1}1,passthrough=on,id=eth2 \
...
```

**Comment by giuseppelettieri** [comment]
pipe0 and pipe1 are not sharing memory, since they have different names. You cannot swap buffers between them. Is this OK? If yes, then you can create pipe1 in the guest, which is better since the passthrough involves the creation of a bunch of kernel threads for synchronization. Can you give any detail on what you need in your setup?

**Comment by ramaza** [comment]
I'm working with a dual-core setup and I'm thinking of the most simple approach to utilize both cores. Splitting application logic by using a Netmap pipe sounds like a straightforward approach.

The final device (an embedded system) does have a real Netmap-enabled Ethernet interface. The problem is that for simulating larger networks of such devices we are in need of running our Netmap application within a lot of Qemu instances which are again interconnected with a Netmap application inside the host.

I do understand that running simulations of complex networks might not align well with the primary use-case of Netmap and Netmap-Passthrough. Although it provides some great advantages.

The problem is that we can't consider adding a Netmap pipe to the architecture of our Netmap application because we couldn't run it inside of the simulation environment based on Qemu + Netmap-Passthrough. That's why I was looking for a workaround (at the cost of performance).

**Comment by vmaffione** [comment]
In this case just create a pipe inside the guest as Giuseppe is suggesting. You won't be able to zero copy between the ptnet interface and the pipe, but I guess it's not a problem for your simulation environment. On your embedded device you will be able to zero copy.

Another solution for scaling to more "emulated nodes" would be to use containers like LXC rather than QEMU. In that case you could just use "veth" pairs instead of netmap passthrough to connect the containers with the host and/or among them. A veth in netmap mode is just a pipe under the hood, so it would be very fast.

**Comment by ramaza** [comment]
Using a container like LXC is an interesting idea. I will give it a try. Thanks!
