### ISSUE TITLE
Spurious packet loss

### ISSUE THREAD

**Issue by an0sv** [luigirizzo/netmap#523]
We are using an Intel 40Gbe card (ie40) and are receiving single (everything goes to a single queue) very high bitrate UDP streams 5Gb/s with a packet size of approx 1400 bytes. 

Everything seems to work just fine with a low CPU load but still we get spurious packet losses.

I have tried to set the maximum rx descriptors to 4096  using ethtool but then netmap complains and state the it can not allocate memory. What is the cause to that? So the maximum we can use is 2048 descriptors.

**Comment by giuseppelettieri** [comment]
To have rings with 4096 slots you need you should increase the maximum size of the netmap rings, which is 36864 bytes by default. Something like this should suffice:
 ``` echo $((1<<17)) | sudo tee /sys/module/netmap/parameters/ring_size```
Note, however, that completely avoiding packet losses at 40G is very hard, even with large packet sizes and large rings.

**Comment by an0sv** [comment]
Thanks that solved my issue

**Comment by davidmpc** [comment]
I also encountered this problem when I was running an application based on netmap. I use iperf3 to test and when the packet pps is up to about 10000, there is a 2.5% packet loss in one second occasionally, so I execute the command:
`echo $((1<<17)) | sudo tee /sys/module/netmap/parameters/ring_size`
but the problem is still there.
So after some trials I change the ring num using:
`sudo echo 4096 | sudo tee /sys/module/netmap/parameters/ring_num`
This issue is solved and there is no packet loss.
I hope this can be useful to anyone may have the problem.

**Comment by seven9417** [comment]
hi，i also encount this problem ，but i can only increase ring_num to 1024，otherwise i cannot open netmap。
