### ISSUE TITLE
Link Reset Question

### ISSUE THREAD

**Issue by sdpetrides** [luigirizzo/netmap#549]
I would like to know more about the importance of waiting for a physical reset. I see some documentation about it in the `pkt-gen` sample but I would like to know a little more about why it is important to reset.

I was writing a simple read-write netmap application and I found that if I did not wait for a reset before or after read or write, I ran in a kernel sync issues. Specifically, if I call `RXSYNC` or `TXSYNC` too recently after an `open` or `close` the link would break and I would not be able to get any traffic. See the error logs below.

```
[  873.986304] 825.932636 [ 202] virtio_netmap_clean_used_rings got 1 used bufs on queue tx-0
[  873.986799] 825.933133 [ 215] virtio_netmap_clean_used_rings got 0 used bufs on queue rx-0
[  873.987333] 825.933668 [ 669] virtio_netmap_init_buffers added 255 inbufs on queue 0
[  874.014256] 825.960590 [ 202] virtio_netmap_clean_used_rings got 0 used bufs on queue tx-0
[  874.014773] 825.961108 [ 215] virtio_netmap_clean_used_rings got 1 used bufs on queue rx-0
[  874.015352] 825.961668 [ 241] virtio_netmap_reclaim_unused detached 1 pending bufs on queue tx-0
[  874.015908] 825.962243 [ 253] virtio_netmap_reclaim_unused detached 255 pending bufs on queue rx-0
[  874.016490] virtio_net virtio3: input.0:id 252 is not a head!
[  874.981715] virtio_net virtio3: output.0:id 3 is not a head!
[  874.986411] net ens18: Unexpected TXQ (0) queue failure: -5
[  876.005679] net ens18: Unexpected TXQ (0) queue failure: -5
[  877.029669] net ens18: Unexpected TXQ (0) queue failure: -5
```

I would just like to know what is failing in this case and the best practices for waiting for the physical reset. Thank you.

**Comment by vmaffione** [comment]
Before a NIC enters netmap mode, descriptors in the NIC RX and TX rings are (or may be) linked to sk_buffs. This means that the NIC and the OS driver can access these buffers (read/write) at any time.
To enter netmap mode, we need to rewrite the descriptors in such a way that they link to netmap buffers.
But the whole replacement is obviously not an atomic operation, so we cannot do that concurrently with the NIC and OS potentially accessing the buffers (note that the OS driver accesses the rings also in the interrupt or NAPI routine). This would lead to kernel crash: for instance the OS driver could call kfree_skb() on a netmap buffer, or something like that.
There is a similar issue when exiting netmap mode.

To solve the race condition, we need a way to tell the NIC and OS driver to stop touching the rings, perform the replacement (in nm_register), and then re-enable NIC and OS driver access.
The only reliable and general way we know to achieve this goal (temporarily disable NIC/OS access) is to bring the link down (e.g. the equivalent of `ifconfig eth0 down`). The link is brought up again at the end of `nm_register`.
Technically speaking, link reset is not a requirement. It's just what happens when you bring the link down and up.

In case of virtio, there is no phyisical link reset reset, but the `nm_register` code may be buggy at least for some Linux versions. When you say "waiting for physical reset" you mean something like the `-w` option of pkt-gen?

**Comment by sdpetrides** [comment]
Thank you for the thorough response.

Yes, by waiting for the physical reset I mean the `-w` or some kind of ` sleep`.

From some basic testing, I have found that `usleep(1000)` at `open` and `close` does the trick.

**Comment by vmaffione** [comment]
Ok, but this is a bug. Which Linux version and distribution are you using?

**Comment by sdpetrides** [comment]
I am using `4.11.0-041100-generic`. More recent versions have an issue with RX after 128 packets. See #543.

**Comment by vmaffione** [comment]
Hi,
 The netmap support for virtio-net has been rewritted from scratch,  to cope with many existing problems, including the ones you describe.
Can you please retry with the current master? Don't use `--no-ext-drivers`, otherwise you will fall back to the old implementation.

I tested also the host rings with TCP traffic and they work fine for me now.

**Comment by sdpetrides** [comment]
I have tested the next `virtio_net` module and I am not experiencing this issue any more. The link does not "break", there are no error messages in the log, and packets are sent and received correct.
