### ISSUE TITLE
Coalesce ixgbe problem

### ISSUE THREAD

**Issue by sinainnet** [luigirizzo/netmap#555]
Hi,

I have a problem with netmap-deriven ixgbe cards, when trying to set rx-usecs using ethtool. Indeed, running the following command:

`ethtool -C <nic-name> adaptive-rx off adaptive-tx off rx-usecs 50
`

The network card is intel 560+ (82599). The netmap version is 11.1 and the ixgbe driver is 4.3.13. The operating system is Ubuntu 1204 LTS with 3.13 linux kernel. I wonder if it's helpful but, the problem seems to be appeared when the link to the nic is up.

I want to know that, this is problem of the patched ixgbe or not?

I will be gratefull if anyone help me.

**Comment by vmaffione** [comment]
What is the problem? I don't see any in our description.
Please use the netmap master branch. Tags are only historical, and not maintained versions.

**Comment by sinainnet** [comment]
The problem is the aforementioned does not affect the rx-usecs parameter. For some reason, I have to use the 11.1 version. I'm not sure that the source of the problem is ixgbe. I've observed that the linux default ixgbe causes the command applies the changes. It left rx-usecs=50!

**Comment by vmaffione** [comment]
netmap should not interfere with you setting that parameter. We only intercept the ethtool calls to change the number of NIC queues and the number of slots per queue.
Are you changing the parameter value while your application is running (i.e., while the ixgbe NIC is in netmap mode)?

**Comment by sinainnet** [comment]
I change it when the NIC is up, but the netmap-driven app is not running. It means, there is no opened netmap socket, but the netmap module is loaded.

**Comment by vmaffione** [comment]
So if I understand correctly your `ethtool -C` command appears to work when you use the `ixgbe` module which comes with your distribution, while it does not work when using the `ixgbe` module provided by netmap?

**Comment by sinainnet** [comment]
Yes.

**Comment by vmaffione** [comment]
Ok. This means that your issue is not related to netmap.
We simply download the drivers provided by Intel on sourceforge.net, patch them (without touching ethtool support) and compile them.
So maybe the issue is due to the particular Intel driver that we are using with ixgbe.
Here https://github.com/luigirizzo/netmap/blob/master/LINUX/default-config.mak.in_#L83
you can see that we are currently using version 5.3.8. It is possible to change it with `--select-version` or by modifying that file.
You can look at the patch  that we apply here https://github.com/luigirizzo/netmap/blob/master/LINUX/final-patches/intel--ixgbe--5.3.8
You can see all the supported ixgbe versions here https://github.com/luigirizzo/netmap/tree/master/LINUX/final-patches

The other option you have is to build ixgbe from the sources of your running kernel. In this case you need to use `--no-ext-drivers=ixgbe` and provide the kernel sources with `--kernel-sources`.

You could try older versions, there are many
