### ISSUE TITLE
TX Ring Not Clearing

### ISSUE THREAD

**Issue by sdpetrides** [luigirizzo/netmap#557]
I have been using the latest virtio_net and noticed that my application was stalling. It was not able to send packets. I traced the TX logjam back down the sequence of connected netmap-pipes to the "physical" link. In this case, the physical link is a virtio_net device.

I found that after `poll(POLLOUT)` or `ioctl(TXSYNC)` calls, the packets were not getting sent. The poll would exit without taking the full timeout and the return value would be positive. However, there would be no additional room on the TX ring. There were no error messages in `syslog` that indicated any kind of failure.

I tried the current master (`1b5361df`) and another commit (`b4ed0de9`). I experienced the issue with both of these commits. Finally, I checked out the `7ec0e64d` commit and I was able to run my application without this TX issue.

Let me know if there is something more specific I can tell you about this issue. Thanks.

EDIT: I have experienced the issue with that last commit. Let me do some more digging on my end.

EDIT 2: I have seen the first error message in `syslog`. This occurs if the downstream pipes are closed after the "physical" link is closed. If the pipes are closed before the link, there is no error message.
```
[ 6955.619207] virtio_net virtio3: output.0:id 19 is not a head!
[ 6955.619507] net ens18: Unexpected TXQ (0) queue failure: -5
```

**Comment by vmaffione** [comment]
Ok, actually there is still a race condition in the way we enter/exit netmap mode for virtio_net adapters.
This would be confirmed if you observed the issue after a virtio_net interface exits netmap mode. Is this the case?

Regarding the commits you mention, I don't think they make any difference, also because nothing changes w.r.t. the TXSYNC part. I think it just happened that you observed the race condition in one case and not in the other.
