### ISSUE TITLE
nm_open on pipe fails

### ISSUE THREAD

**Issue by AmbrSb** [luigirizzo/netmap#585]
Hi,

Running this line of code on FreeBSD 11.0-RELEASE-p1 #0 r306420:

`nm_open("netmap:pipe{1", NULL, 0, NULL);`

nm_open returns NULL and prints the following message:

`462.600023 nm_open [608] NIOCREGIF failed: Device not configured pipe{1`

Am I missing something?

```
clang --version
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: x86_64-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by vmaffione** [comment]
That release contains very old code, that does not support this kind of operation (creating an ephemeral port on the fly, to use as a parent adapter for the pipe).

To access a more recent netmap code you have different options:
  - use FreeBSD-11-STABLE (latest code)
  - use FreeBSD-12-STABLE (latest code)
  - use FreeBSD-12.0 (almost latest code)
  - wait for the next FreeBSD-11.3-RELEASE.

Of course you need to keep in mind that STABLE snapshot are mostly for testing (so have options that slow down the system).

**Comment by AmbrSb** [comment]
OK thank you for the clarification. So, is there any way to have netmap pipe-based IPC in FreeBSD 11.0?

**Comment by vmaffione** [comment]
Have you tried to use something like `netmap:em0{1`, if `em0` is an existing network interface? That may be a strategy, although you would still be using very old code.

Otherwise you could just import the latest netmap code from https://github.com/freebsd/freebsd/tree/stable/11 and recompile your 11.0-RELEASE kernel. You should import files from `sys/dev/netmap`, `sys/net/netmap*.h`, and `tools/tools/netmap/` (for applications). Also you will need to fix some compilation issue in `sys/dev/cxgbe` and maybe some few other drivers.

**Comment by vmaffione** [comment]
Also, you will need to align `sys/conf/files`, to include all the netmap source files.
