### ISSUE TITLE
lock a buffer after it has been transmitted

### ISSUE THREAD

**Issue by linoferrentino** [luigirizzo/netmap#588]
Hi,

In my application it would be nice to access a buf_idx after it has been transmitted.

This is the scenario. User code copies some data to a slot. We advance head and call ioctl. However we don't yet want to relinquish to kernel the old buffer as we might need it in the near future in case we need to retransmit it.

I have requested extra buffers from the application and this is working fine in the receiver part (if I receive an out of order packet I simply park it in a separate extra ring hoping to fill the holes later), however in the sending part this is not so easy, because the documentation tells that packets from tail to head-1 are "explicitely" assigned to kernel.

I would like to have something like:

User writes to slot buf_idx
`ts->flags |= NS_HOLD; //something like that`

and then the usuall

```
  advance head
 
  ask ioctl to send...

```
the kernel will have to mark this slot as "write complete..." so that we know that the
transmission is over.

And now I will reference the _old head_, and save it in an extra buffer

```
take extra buffer index

put this extra buffer index to the slot which was set as HOLD

reset the HOLD flag, thus telling netmap kernel side that now it can use it.

if there is not an extra buffer just resort to a "normal" memcpy
in a buffer and reset the HOLD flag

when the other side tells us that buffers are arrived we simply
put the extra buffers again in the free list.

```

In practice I would like the possibility to refer to buffer indexes before the head in the txring in a safe way.

**Comment by vmaffione** [comment]
Hi, the easy answer is that what you want to do cannot be achieved with the current netmap ring abi/api.
However, I think there are ways you can get what you need. There are two issues here. 

The first one is that the struct netmap_ring does not export the head pointer of the underlying real ring (e.g. nic ring), so that you don't know what is the last buffer that was actually transmitted. There is however a new (still undocumented) feature that we call "csb mode", that is an alternative mode to open netmap ports and interact with them. In this mode the kernel does not read ring.head and ring.cur, and does not updates ring.tail. Instead, your application needs to allocate an array of structs (I.e. the csb), which contains this information. The interesting part is that the csb also contains a pointer called `hwcur`, which actually exports the underlying nic head. You can find an example in `utils/sync_kloop_test.c`.  In this mode, you can't use the sync ioctls, because the sync work is carried out either by an in kernel event loop, or in the context of a write syscall on an eventfd object.

The second problem is that netmap does not guarantee that the tx buffers that you submit by advancing head will not be swapped out with something else. For instance, netmap pipes (and maybe zcopy monitors) actually swap those buffers to implement zcopy forwarding, and there is nothing you can do about that. However, all the other ports will not swap, and you will find the completed tx buffer still there.

**Comment by linoferrentino** [comment]
The fact that the buffers might be swapped to something else might not be too much important _if_ the kernel does not change data, that is swapping them into a rx ring overwriting content.

That is, if I know that my data is in buf_idx X that will be true also if internally this buf_idx changes owner, for example if it is swapped to a pipe, as long as noboby has written to it.

In my application I have complete control of who creates the netmap arrangments (rings and pipes) so I think that this issue can be handled.

I will study better this csb mode, thank you.

**Comment by vmaffione** [comment]
The kernel will never change the data on tx buffers.

**Comment by giuseppelettieri** [comment]
In the latest implementation, pipes no longer swap buffers (zero copy monitors still do). The problem, however, is a different one: in a zero copy setting, nothing can prevent other applications to swap the slots (think of a pipe to a netmap bridge process) and/or to change the buffer contents. What you need is a way to open a port and say that you do not allow any of the above. I have been thinking to this for a while and I have some ideas on how to implement this, but I cannot give any schedule.

**Comment by linoferrentino** [comment]
Thank you very much
