### ISSUE TITLE
reading one rx queue with multi-thread

### ISSUE THREAD

**Issue by lkkey80** [luigirizzo/netmap#622]
Can we read one rx-queue with multi-thread? For example, nm_open 'netmap:eth0-0/R' multi times , get multiple separate nm_desc and read the same rx-queue with multiple threads at the same time.

**Comment by vmaffione** [comment]
Yes, but you need to serialize the access to head and cur, e.g. use locks. Since this is expensive, you may probably want to consider a different architecture. Use the lb application (in the netmap repo, see 'man lb') to distribute the traffic from eth0-0 to N netmap pipes, and run your business logic in a lockless way on each pipe (using a different thread).
