### ISSUE TITLE
 netmap_obj_free  ouch, double free on buffer xxx

### ISSUE THREAD

**Issue by lkkey80** [luigirizzo/netmap#624]
I allocated many extra buffers and replace ring's slot buffer with extra buffers. But I encountered the following issue when my app exits:
netmap_obj_free           ouch, double free on buffer 71
netmap_extra_free         breaking with head 70

I guess that is triggered by ' replace ring's slot buffer with extra buffers', but is there a way to deal with it without modifying Netmap's source code?

**Comment by lkkey80** [comment]
It seems that I need to re-build the extra buffers list before call nm_close, but will netmap go to an incosistent state if my app crashes unexpectedly and can't rebuild the extra buffers list ?

**Comment by lkkey80** [comment]
Will memory leak happen if I failed to rebuild extra buffer list for some reason, eg. crash ?

**Comment by vmaffione** [comment]
Yes, that's unfortunately a shortcoming of netmap, because there is no internal reference counting in the netmap allocator. However, even leaked buffers are returned to the kernel when all the users of the netmap allocator are gone. This typically happens when you stop all of your netmap applications
