### ISSUE TITLE
Are there any performance guides?

### ISSUE THREAD

**Issue by Gymmasssorla** [luigirizzo/netmap#643]
Are there any performance guides to NETMAP, perhaps how to correctly set Pthread affinity or something else? How to correctly parallelize queues to achieve the best performance?

**Comment by Gymmasssorla** [comment]
Also, I think that using multiple threads to work with TX rings won't increase performance because all we need to do with TX rings is fill them with our frames and call `ioctl(fd, NICTXSYNC, NULL)`, isn't it?

**Comment by vmaffione** [comment]
Yes. You should use multiple hardware queues (each one corresponding to a different netmap ring) and have each thread processing a single ring (or a couple of RX/TX rings).
In that case you should `nm_open()` each ring (or couple of RX/TX rings) separately, so that each `ioctl(TXSYNC)`, `ioctl(RXSYNC)` or `poll()` only acts on a single ring (or ring couple).

**Comment by vmaffione** [comment]
You should design your software in such a way that you can flexibly change the association between rings and thread, and then experiment with your real workload to see which strategy works best.

**Comment by Gymmasssorla** [comment]
Thank you!
