### ISSUE TITLE
Host RX does not recognize incoming packets when generic rings > default

### ISSUE THREAD

**Issue by johalun** [luigirizzo/netmap#664]
Hi
FreeBSD 13-CURRENT r354145, running in bhyve. Tested with em and virtio drivers.
dev.netmap.admode=2
dev.netmap.generic_rings=[anything larger than 1]

With this configuration the host rx does not longer wake up from poll for incoming packets. After poll timeouts, I can see new packets in the ring.

The file descriptor is opened with `nm_open("netmap:vtnet0^/R")`

**Comment by vmaffione** [comment]
Why would you want `generic_rings > 1` if `em0` and `vtnet0` have just 1 ring couple ?

**Comment by johalun** [comment]
I want to do development in bhyve without needing real hardware with multi queue support.  Maybe I misunderstand with generic rings are for? Please note that I am running in emulated mode. Another things is, all incoming traffic to the nic seems to come in ring 0. Is there a way to distribute it across all rings in emulated mode?

**Comment by vmaffione** [comment]
`vtnet0` and `em0` should have only one RX ring and one TX ring. Maybe you thought that by using emulated netmap mode and incrementing `generic_rings` you would have got more rings? If yes, that is not how it works. First, you should not use emulated netmap mode, since you have native support for both `vtnet0` and `em0`. Second, `generic_rings` is an old hack that is used to tell netmap emulated mode how many ring pairs the NIC has, since there is no generic way to know it. But the value must match the real number, otherwise things won't work.

**Comment by johalun** [comment]
I see. I started to suspect that was the case. Thanks for clarifying! Even so, emulated mode with extra rings did enable me to do a lot of the development/testing with bhyve which is nice. I guess it's time to move to real hardware for proper functionality.

**Comment by vmaffione** [comment]
Yeah, if you feel adventurous you could try to run a FreeBSD guest with one (or more) `ptnet(4)` interface(s), passing through a multi-ring vale(4) port or multi-ring netmap pipe port. That would require a modified version of QEMU/KVM (over Linux), however.
