### ISSUE TITLE
Bridging veth and NIC

### ISSUE THREAD

**Issue by leoll2** [luigirizzo/netmap#713]
Hello,
I have two machines (let's say host1 and host2) running Linux Containers in them.
Each host has a 10G NIC (x710-da2), exposing interfaces named enp4s0f0. 
The two machines are directly connected with an Ethernet cable.
My goal is to use netmap to exchange packets between containers of these two hosts. To do so, I create a veth pair between each guest and its host, then I use 'bridge' to connect the veth port to the physical interface.
Unfortunately, when I try to create the bridge, the command fails with this error:
```
llai@host1:~/netmap$ sudo bridge -v -i netmap:veth_0_host -i netmap:enp4s0f0
bridge built Jul 19 2020 11:42:49

enp4s0f0: Cannot allocate memory
109.794312 main [266] cannot open netmap:enp4s0f0
```
dmesg does not show any significant error message. If useful to debug, `parameters/if_size` is set to 2048, while `parameters/ring_num` is 200. I've also tried to reduce the number of NIC rings with ethtool down to 16, still doesn't work.

What could be causing this issue? Am I overlooking anything? Also, is this the correct way to connect different containers? I know that in this simple case I could assign the NIC to a container, but this solution would be unfeasible if I had dozens of guests.

_Note 1: pkt-gen between the hosts (no containers involved) works fine at line rate.
Note 2: pkt-gen between a guest and its host (through the veth) works fine
Note 3: pkt-gen between guests of the same host (through vale switch) works fine_

**Comment by jhk098** [comment]
It looks like you are doing it right. And yes, that's the correct way to connect different containers.
I tried to reproduce your problem on a laptop (with 16GB RAM), bridging one end of the veth pair to an `e1000e` device, but I don't see the issue.

I think the error message `enp4s0f0: Cannot allocate memory` it's not produced by netmap, although it does cause the `nm_open()/nmport_open_desc()` to fail. It looks like the error message is produced by the driver.
What is the driver that your NIC is using ? ` ethtool -i enp4s0f0 | grep driver`

How did you compile netmap? Are you sure you are using the modified `veth.ko`, as produced by netmap? Same for the NIC driver?

Have you tried the same experiment with a different NIC model (also on a different machine)? In this way you can verify that the issue is driver-related.

Regarding your note 3, did you attach one end of each veth pair to the vale switch to achieve your configuration, e.g.:
````
# ip link add v0 type veth peer name v1
# vale-ctl -a vale0:v0
# (move v1 to the guest namespace)
````
and so on for each guest container ?

**Comment by leoll2** [comment]
Thanks @jhk098 for the reply.
My NIC is using the `i40e` driver patched by netmap. Both `i40e.ko` and `veth.ko` I'm using are those generated by netmap.
I have tried with another identical interface (enp4s0f1) using the same driver, and it fails.
I have tried with another interface using a different driver (tg3, not patched) and the command gives no error.
Unfortunately I do not have a NIC of different model but same driver (i40e).
I have a second machine with the same hw/sw configuration, I get the same error.

About note 3, yes I do exactly that.

**Comment by jhk098** [comment]
You could try to instrument `nmport_open()` (see `libnetmap/nmport.c`) with some additional `printf` statements, to figure out what exactly fails and prints that `enp4s0f0: Cannot allocate memory` message.

**Comment by leoll2** [comment]
It fails executing [this ioctl](https://github.com/luigirizzo/netmap/blob/6c4a6320245e865f66cc1e721a935a53b4e79a06/libnetmap/nmport.c#L584), more specifically when assigning the iommu group [here](https://github.com/luigirizzo/netmap/blob/6c4a6320245e865f66cc1e721a935a53b4e79a06/sys/dev/netmap/netmap_mem2.c#L748).  

Setting netmap in verbose mode helped me finding the issue, indeed I get this error in dmesg:
`[507625.093147] 794.437329 [ 747] nm_mem_assign_group       iommu group mismatch: 0 vs 18`

veth is in group 0, enp4s0f0 is in group 18.
The problem looks very similar to issue (#688), where the solutions could rebooting the machine with iommu disabled.
Is rebooting strictly needed or is there any workaround? 
I ask because I run on a server shared with other users, where rebooting can be annoying.

**Comment by jhk098** [comment]
I think the problem would go away if you managed to use separate netmap allocators for the two devices (which are in different IOMMU groups). Right now they are trying to use the same default global netmap allocator (`id = 1`), hence the failure.
However, I don't know if there is a direct way to do that.

A workaround that may work is the following.
Create a VALE port
````
$ sudo pkt-gen -i vale:0
````
so that this will trigger the creation of a "private" memory allocator, with `id = 2`. Leave the process running, so that the netmap VALE port will keep the allocator alive.

Then run bridge using the "@2" syntax to ask netmap to use the allocator with `id 2` for one of the devices:
````
$ sudo bridge -i netmap:enp4s0f0 -i netmap:veth0@2
````
If this worked, you will see "zerocopy NOT supported". Now you can stop the pkt-gen process, so that the VALE port will be destroyed. However, the netmap allocator with `id = 2` will stay alive, since it's now referenced also by the netmap port associated to `veth0`.

**Comment by giuseppelettieri** [comment]
I agree with @jhk098, using separate allocators would fix the problem. 

Unfortunately, @jhk098 is also right in noting that there is no direct way to create a new allocator and you have to create a dummy VALE port.

Rather than leaving a netmap app running, though, it is probably better to create a persistent VALE port:
```
$ sudo vale-ctl -n vi0
```
You can then read the memory region identifier with
```
$ sudo vale-ctl -g vi0
```
Moreover, in the latest master (pushed just now) ```nmport_open``` lets you refer to the allocator of another port by port name, instead of by memory id, e.g.:
```
$ sudo pkt-gen -i vale0:0@share=netmap:vi0
```

**Comment by leoll2** [comment]
Thank you both for the support! I managed to bypass the problem thanks to the dummy VALE port trick.

Just a couple of things before closing the issue, if you want to answer:
1) When I transmit in one direction (host1 -> host2), the throughput settles around 10 Mpps "only". If I stop the application, then transmit for a while in the opposite direction (host2 -> host1), then stop, then restart transmitting in the original direction, I eventually reach the limit of 14,88 Mpps. What could be crippling the initial throughput to 10 Mpps?
2) What if instead of bridge I want to use vale-ctl to connect one or more containers to the NIC? Doing
```
sudo vale-ctl -a vale0:vi0
sudo vale-ctl -a vale0:enp4s0f0
sudo vale-ctl -a vale0:veth_0_guest
```
results in the iommu mismatch error, and I don't think that something like `sudo vale-ctl -a vale0:enp4s0f0@2` is valid syntax.
 An alternative would be attaching persistent ports to the switch, then moving them to the container namespace (after removing the `NETIF_F_NETNS_LOCAL` flag): it seems to work after quick tests, but it is not officially supported as far as I know.

Thanks again!

**Comment by jhk098** [comment]
Regarding (1), the lack of pps reproduciblity may be due to many factors. Your way to trigger it may be misleading. For instance, you should check if the performance drop happens when pkt-gen (or other netmap app) migrates to different CPUs in one of the hosts. Specially if your machine is dual socket, running the application from a CPU on the remote socket (w.r.t. the NIC PCI bus) may cause the issue. Another cause may be a sudden increase in the interrupt rate (typically on the receive side), so you should monitor also that and see if there is some correlation. (I assume you have ethernet flow control disabled).

Regarding `vale-ctl`, `sudo vale-ctl -a vale0:enp4s0f0@2` is not a valid syntax because `vale-ctl` is not using the new `libnetmap.h`, which introduces that `@` syntax. However, you can use the `-m` option of `vale-ctl`, which lets you select a given memory allocator by id, and therefore achive the same result. So `sudo vale-ctl -a vale0:enp4s0f0 -m 2`.

The `NETIF_F_NETNS_LOCAL` flag should actually be removed, indeed, like you did. If you manage to test it for some time, and don't see problems, you may also open a pull request to make the change happen.
