### ISSUE TITLE
Do not perform an interface UP/DOWN when there is at least one netmap consumer attached.

### ISSUE THREAD

**Issue by mkaniewski** [luigirizzo/netmap#730]
Hi,

In my application there is one worker (i.e. a separate process) per every interface queue:
```
worker 0 -> nm_open("netmap:igb0-0");
worker 1 -> nm_open("netmap:igb0-1");
worker 2 -> nm_open("netmap:igb0-2");
....
```
Workers sometimes needs to be restarted. However there is always at least one worker that is still active and attached to an interface.

My problem is that a worker restart results in an interface DOWN/UP cycle. It happens because when the worker stops then the netmap descriptor to the interface queue is closed and in a result the driver performs the interface reset (same happens when the worker starts and the netmap descriptor is created). This is problematic because restart of a one worker results in a suspension of all other workers which must wait until interface perform the DOWN/UP cycle.

This is happening on FreeBSD 12. On FreeBSD 11 an interface UP/DOWN cycle was performed only when the first netmap consumer was attaching to the interface queue (or wheb the last netmap consumer was detaching from the interface queue). I am not sure but it looks like this behavior was changed in 566ae405779670ebdff0b0b048842e430e2f09ae.

Summarizing, I would like to see an interface UP/DOWN only when:
1. First netmap consumer attaches to the interface queue,
2. Last netmap consumer detaches from the interface queue.

Is it possible to get this behavior with the current API? If not then what changes in the netmap code would be required? I could work on it however I would probably need some tips.

Thanks.

**Comment by jhk098** [comment]
The change in behavior happened when netmap gained support for per-ring netmap mode. IOW, now you can turn only a subset of the NIC rings in netmap mode, while the others will stay connected to the host stack (thus not in netmap mode).
Before the change, even if you opened just `netmap:igb-2`, all the rings (TX and RX) were actually moved to netmap mode.

The NIC reset is currently a convenient and safe way to turn one or more rings to netmap mode (or back to normal mode). It may be possible to do the same without a reset, but that looks like something that requires a lot of effort.

Instead you can achieve your goal without any code change. Just run a system daemon at startup that opens all the rings and waits forever:
````
nm_open("netmap:igb");
pause();
````
This will keep all the NIC rings always in netmap mode, and therefore your workers starting or stopping will never cause NIC resets.

**Comment by mkaniewski** [comment]
Thanks for the great suggestion! This should work for me.

I would only have one question. My worker process may exit ungracefully and corrupt mapped netmap structures. I am wondering if there is any difference in how netmap will deal with that if I have a daemon with constantly opened rings. In the daemon process I can keep a copy of the initial ring states and "restore" them after every worker crash. Do you think it makes sense to do this? I know that netmap can itself detect rings corruption and reinitialize them if required therefore it may be pointless to do anything special in the daemon.

**Comment by jhk098** [comment]
Well, every time you open a netmap ring, a brand new `struct netmap_if` is allocated and the `struct netmap_ring` corresponding to the newly opened ring is initialized. So I think that if you are able to detect a crash, you could be conservative and assume all the `struct netmap_if` and `struct netmap_ring` structures are now corrupted, and thus close all the rings and reopen them all.

**Comment by jhk098** [comment]
Netmap does a partial reinit, only of the ring indexes, in case of txsync/rxsync error. It does not restore all the other fields in `netmap_if` and `netmap_ring`. I think memory corruption is unavoidable for a system based on shared memory, where you trade safety for performance.

I also think what you propose should work, although it's a hack. You should probably do the reinit in the worker itself. The `struct netmap_if` shouldn't be a problem, because a new one is allocated for each netmap open, in any case.

**Comment by mkaniewski** [comment]
Thanks for the clarification.

If I understand correctly this is all a consequence of an approach in which all processes using netmap hardware ports have an access to one global shared memory region where all netmap related structures are placed. Therefore one misbehaving process can potentially affects all other processes using netmap e.g. by writing random data to `netmap_ring` structures. So even if I will restore one `netmap_ring` structure then there may still be other structures that were damaged by the misbehaving process.

@giuseppelettieri I found your comment (https://github.com/luigirizzo/netmap/issues/375#issuecomment-336436051) in which you stated:
```
Please be aware, however, that this implicit sharing of memory among all hardware ports is legacy netmap behaviour and may change in the future. A new syntax will be made available to specify more precisely when and how you want to share memory.
```
Was this new syntax ever implemented? It sound like it could be used to limit the negative impact of the misbehaving process to only those structures that are used by this process.

**Comment by giuseppelettieri** [comment]
> Was this new syntax ever implemented? It sound like it could be used to limit the negative impact of the misbehaving process to only those structures that are used by this process.

More or less. In my opinion, netmap should have defaulted to per-process, or at least per-port, private memory, with sharing only enabled when explicitly requested. But there were disagreements about how this should have been orchestrated and progress stalled.

In the current implementation you can get a private memory in the following, clumsy way.
1. First create a dummy persistent VALE port (VALE ports are the only ports that automatically get a private memory):
```vale-ctl -n vi0```
2. Then get its private memory id:
```vale-ctl -g vi0```
Assume its 2.
3. Then you open the port you are really interested in and use memory region n. 2:
```pkt-gen -i eth0@2```
4. Now you can optionally remove the dummy VALE port, so that the private memory will be automatically released to the system when your netmap application terminates:
```vale-ctl -r vi0```

Of course you can do all of the above programmatically, by issuing the appropriate `ioctl()`s.

If you are using libnetmap, you can fuse points 2 and 3 by calling `nmport_open("netmap:eth0@share=netmap:vi0")`.

**Comment by mkaniewski** [comment]
@giuseppelettieri Thank you for the example! I didn't know about this functionality. I will give it a try.

I am closing the issue. At this point all my questions was answered. Thank you all.
