### ISSUE TITLE
High Performance NIC - Linerate x Netmap x NIC

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#825]
Hi, folks.

1) Are there any 82599, capable of sustaining linerate speeds with different small packet sizes? (64, 65, 66, 67, 68 bytes for example).

2) Would this be driver related? If yes, do you recommend any ixgbe driver version in this case?

3) If ixgbe, is not a solution, would i40e, rule out all these problems ?

Thanks guys.

**Comment by jbrandeb** [comment]
Line rate at what link speed? If just 10Gb/s then the x550 may be able to get there. I don't think this is driver related but you may want to make sure your interrupt rate is set high enough (ethtool -C) to be able to keep the rings from overfilling while waiting for cleanup of the ring. Otherwise, the X710 or E810 at 10Gb/s should be able to maintain line rate at the smaller packet sizes.

**Comment by Fr3DBr** [comment]
Hi, Jesse.

This is more about 40G / 100G. :)

Sincerely,

**Comment by Fr3DBr** [comment]
Thanks for the input on this. :-)
