### ISSUE TITLE
Select/poll behavior questions

### ISSUE THREAD

**Issue by scott-aos** [luigirizzo/netmap#884]
Hello! I've got some questions around select/poll behavior in a few different scenarios. I was unable to find definitive answers to these but apologies in advance if I missed a piece of documentation. Some of the answers are probably obvious, but confirmation would be great, so thank you in advance.

1. Does select/poll always sync both rx and tx? E.g., if I select/poll the netmap file descriptor for read, will tx be synced on return?
2. Is select/poll on both netmap and non-netmap file descriptors simultaneously supported? What will rx/tx sync state be on return if the select/poll returns as a result of an event associated with a non-netmap file descriptor?
3. If select/poll on the netmap file descriptor returns due to timeout, what is the rx/tx sync state?
4. What support is there for multiple threads performing select/poll on the same netmap file descriptor? E.g., is it possible to have a thread dedicated to tx that selects/polls for write, and a separate thread dedicated to rx that selects/polls for read? Assuming the tx thread only manipulates state associated w/ tx queues and the rx thread only manipulates state associated w/ rx queues, is this supported/safe?

Thank you!

**Comment by jhk098** [comment]
I'll try.
1. Yes, look at `NR_NO_TX_POLL` and `NR_DO_RX_POLL` in netmap(4) or sys/net/netmap.h
2. There is nothing special to support. The poll() or select() implementation will call the poll callback associated to each file descriptor, and each one should return the events that are ready. The netmap poll callback has side effects, that is calling TXSYNC and/or RXSYNC, and you should take this into account.
3. I guess you mean netmap ring state. In case of RX rings, a timeout indicates that no packets were received since the call. So it will be `ring->head==ring->cur==ring->tail`. For TX rings, you would have the same situation, indicating that no TX slots were freed for reuse since the last call (unlikely, unless the timeout is really really short).
4. Yes absolutely, and you can have an even finer granularity, e.g. one thread for each RX/TX ring couple, or one thread for each RX ring, and one thread for each TX ring, or any combination that you wish. However, you should normally have a separate netmap file descriptor (on the same NIC, in this case) for each thread. A netmap file descriptor is an object bound to a set of rings of a NIC (1 ring, 2 rings, or many rings). Any poll/select/txsync/rsync operation that you perform on the file descriptor will operate only on the rings that you have bound at register (netmap open) time. You should not have overlaps, otherwise you will get contention (it would be safe but inefficient and not useful). If you look at pkt-gen, the -p option will cause pkt-gen to spawn multiple threads bound to separate TX/RX rings (if NIC is multiqueue).

**Comment by scott-aos** [comment]
Thanks for the comprehensive answer! I'll check out pkt-gen as well.
