### ISSUE TITLE
virtio-net-header handling in driver

### ISSUE THREAD

**Issue by kalyazin** [luigirizzo/netmap#89]
Hi,

As I can see from the code, virtio-net-header handling is done inside an application (e.g., -H option in pkt-gen) rather than in netmap virtio driver.
Why has such a design decision been chosen? Wouldn't it be the right way to go to encapsulate the driver-specific stuff into the driver itself (i.e., handle virtio-net-header inside virtio_net.c patch)?

**Comment by vmaffione** [comment]
Hi @kalyazin , yes we are already discussed this internally in the past. What you say is correct, and will be addressed soon. There is however a compromise between not exposing this hardware specific stuff and performance reasons (using a 2 elements Scatter Gather array with the virtio API) that has to be taken into account.

**Comment by kalyazin** [comment]
Hi @vmaffione,

Can it be solved in a similar way to the Linux kernel driver (push the virtio header into the packet headroom if possible)?
```
	sg_init_table(sq->sg, MAX_SKB_FRAGS + 2);
	if (can_push) {
		__skb_push(skb, hdr_len);
		num_sg = skb_to_sgvec(skb, sq->sg, 0, skb->len);
		/* Pull header back to avoid skew in tx bytes calculations. */
		__skb_pull(skb, hdr_len);
	} else {
		sg_set_buf(sq->sg, hdr, hdr_len);
		num_sg = skb_to_sgvec(skb, sq->sg + 1, 0, skb->len) + 1;
	}
	return virtqueue_add_outbuf(sq->vq, sq->sg, num_sg, skb, GFP_ATOMIC);
```

**Comment by vmaffione** [comment]
Yes, that is what I meant, you can use a 2 elements SG, where the first is a zeroed virtio header. The netmap driver could probably use a single statically allocated virtio header for all transmission. But you have the overhead of using 2 virtio descriptors per packet, instead of 1 per packet. How much this impact the performance has to be measured.

It may exist another solution that involves reserving some headroom in the netmap buffer, in a way that is transparent to the application, so that you could still manage to use 1 descriptor per packet.

**Comment by kalyazin** [comment]
Right, I fully understand the first point. It's clear that it's bad for performance to use 2 descriptors per packet. 
Now I'm trying to assess the latter one. Apparently you want to say that the driver doesn't know if there is a headroom in the packet or not. If it's the case, then it's not safe to push the virtio net header into the headroom (because there might not be a valid memory for it). Am I right or it isn't an issue?

**Comment by vmaffione** [comment]
I using 2 descriptors per packet really impacts performances has to be seen, let's not assume it. In any case, since userspace API compatibility is more important, using 2 descs per pacet can be an intermediate step towards a better solution.

Afaik, currently there is no headroom, netmap buffers are just contiguos 2K (or 4K) memory buffers. The userspace application prepares the ethernet frame layout starting from the beginning of the netmap buffer, so no headroom. Since there other NICs (apart from virtio-net) that need some "annotation space" before the actual ethernet frame, there was some idea in the past to always reserve a fixed amount of space (e.g. 128 bytes) at the beginning of each netmap buffer, so that the userspace application always prepares its ethernet frame starting from byte 128. In this way, If the specific driver needs part of the 128 bytes headrom, it is free to use it.

**Comment by kalyazin** [comment]
Btw, why hasn't this agreement (about 128 bytes of headroom maintained by the application) been used eventually?
Looks like the proper solution for this problem would be existence of a dedicated data structure for a packet (like it has been done in DPDK with mbuf or ODP with odp_packet_t), which would encapsulate all the netmap implementation details, including headroom. However this change would require redesign of the netmap API and probably make it much more complex for a user.

**Comment by vmaffione** [comment]
Yes, one of the strong point of netmap is precisely avoid to use
"non-trivial" packet representation, and all the involved overhead.
The 128 bytes headroom would not be maintained by the application, would be
transparent to the user. The application uses the macro NETMAP_BUF() to get
the buffer space, and this would return 128 bytes from the beginning of the
buffer.

However, as I said, the possibility to use this trick is still under
evaluation.
​

**Comment by kalyazin** [comment]
Well, it looks like the situation is clear to me now.
Thanks for the discussion!

**Comment by vmaffione** [comment]
This issue has been addressed, closing
