### ISSUE TITLE
Must run application as root to access netmap:ethX interface

### ISSUE THREAD

**Issue by john-gress** [luigirizzo/netmap#96]
I am running on CentOS 6.5 with an updated kernel: 2.6.32-573.7.1.el6.x86_64; using netmap-libpcap and netmap patched ixgbe drivers. My application has the following setcap privileges: cap_sys_nice,cap_net_raw,cap_net_admin=eip

When I call pcap_activate, I get the following error: 
`netmap open: cannot access netmap:eth7: Permission denied`

If I run the application as root, I am able to access netmap:eth7 and receive packets.

Do I need to use different setcap privileges?

**Comment by stefano-garzarella** [comment]
Hi john,
maybe you just change the permissions of /dev/netmap.

Cheers,
Stefano

**Comment by john-gress** [comment]
Hi Stefano,

Using `chmod o+rw /dev/netmap`, my application starts. But the permissions need to be changed everytime the driver is loaded. Shouldn't the driver create the device with the correct permissions?

Regards,
John

**Comment by stefano-garzarella** [comment]
Hi John,
it depends. For us the correct permissions are to allow the access only for the administrator (root) because netmap shares kernel memory with the user space.
You can create a simple script that loads a netmap module and then it can change the permissions of /dev/netmap.

Otherwise you can modify the netmap code on this line (https://github.com/luigirizzo/netmap/blob/master/sys/dev/netmap/netmap.c#L3178) to create /dev/netmap using the permissions that you prefer.

Cheers,
Stefano
